### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by mjastrzebowski**
Hi, 
I didn't want to change too much HTML, so I don't use any framework. I think I prepared it in a pretty clean way and easy to change - if the page does not grow up too much. 

I'm still going to work with it, specially with sidebar on license preview and maybe some changes with breadcrumbs.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Personally, I don't like reinventing the wheel. A framework will reduce the amount of custom CSS needed and ensure that things work good.

But anyway that's my opinion only...

**Comment by benbalter** [comment]
@mjastrzebowski thanks for the pull request (and sorry for the radio silence). Any interest in still seeing this through? If you merge in master to resolve the conflict, would :heart: to merge.

**Comment by mjastrzebowski** [comment]
@benbalter thanks for response! I'll merge this with master and update pull request in a few days.

**Comment by bkeepers** [comment]
This looks great! Thanks for taking a pass at this, and sorry for the delay in getting it merged!

**Pull request merged**
