### PR TITLE
Remove unnecessary (c) symbol from licenses

### PR DESCRIPTION
**Pull request by xtqqczze**
**Supersedes #735**

The symbol (c) is redundant when compbined with the word "Copyright"

### CODE REVIEW

**Comment by waldyrious** [comment]
> Follow-up to #735

And #737, for completeness.

**Comment by xtqqczze** [comment]
> I agree it is redundant, since it plays the same role as the word "Copyright". Quoting Wikipedia's [Copyright notice § Form of notice](https://en.wikipedia.org/wiki/Copyright_notice#Form_of_notice):
> 
> > The notice for visually perceptible copies should contain all three elements described below. They should appear together or in close proximity on the copies.
> >
> > 1. The symbol © (letter C in a circle); the word “Copyright”; or the abbreviation “Copr.”
> > 2. The year of first publication (...)
> > 3. The name of the copyright owner (...)
> >
> > Example: © 2012 Jane Doe 
> 
> Note the "or" in the first item of the list. The `(c)` is one of three possible representations of the same concept. So unless the license requires usage of the "Copyright (c)" format, I agree we should generally normalize (all licenses, not just MIT) towards just "Copyright".

_Originally posted by @waldyrious in https://github.com/github/choosealicense.com/pull/737#issuecomment-632008293_

**Comment by mlinksva** [comment]
I agree that (c) is redundant in the presence of Copyright. However, seeing all of these change (aside: is Zlib omitted intentionally?) I'm a little reluctant because:

- The redundant usage is nearly omnipresent in copyright notices with these licenses in the wild; people are used to that
- I don't consider it important to educate anyone on this redundancy
- The license texts in this repo aren't where reform happens, it's relatively trailing edge, reflecting what is in the wild

Happy to read about why this is an important change to make, here. Otherwise, I'd suggest taking the proposal to https://github.com/spdx/license-list-XML ... if it is accepted there, I'd take it onboard here immediately.

Another question: why not just "©" instead of just "Copyright"?

**Comment by xtqqczze** [comment]
@mlinksva Thank you for pointing towards the [spdx/license-list-XML](https://github.com/spdx/license-list-XML) repo, I was not aware that it was on Github. I agree that would be the best place to make any changes.

**Comment by waldyrious** [comment]
> Another question: why not just "©" instead of just "Copyright"?

I can think of a few reasons, off the top of my head:
- Ease of input
- Searchability
- Explicitness (spelled out)
- Readability ("copyright &lt;year&gt; &lt;author&gt;" can sort of be sounded out as a sentence)
- Precedence

Granted, none of these are particularly strong arguments, but perhaps cumulatively they command sufficient weight to make spelled-out "Copyright" a more reasonable choice? I don't actually have a strong opinion on this.

On a separate, but related note: if you would instead suggest using © rather than (c) or (C), then maybe that would be a more straightforward stance to adopt. The reason to use the latter was just a technical limitation; it doesn't bring any readability benefits, and even though it makes writing slighly more inconvenient, writing copyright notices is not something that one does very often anyway.

**Comment by mlinksva** [comment]
@waldyrious I don't see explicitness, readability, or precedence as advantages for "copyright" over "©" -- how does one read the latter other than "copyright"? I'm not sure what precedence means -- in what sense does the word have precedence over the symbol. You're right about ease of input and search. I wasn't suggesting © rather than (c) though that probably makes sense as a tiny improvement.

I opened a dozen books near my desk and all but one had "Copyright © YYYY", and that one had "© YYYY".

I'm going to close this as I do think it'd be nice if OSS licenses skipped the word and/or replaced "(c)" with "©" but again, I'd rather consume that change from a consensus arrived at by SPDX rather than push it.

**Comment by waldyrious** [comment]
I won't argue for "copyright" over "©" — as I said, my arguments were all pretty weak ones individually. I might explain my reasoning in more detail if you're curious, though.

> I wasn't suggesting © rather than (c) though that probably makes sense as a tiny improvement.

Is this also something you'd prefer SPDX to take the lead on, or would it be OK to do in choosealicense.com?

**Pull request closed without merging**
