### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by haacked** [comment]
This looks like a Work in Progress. Maybe change the title to "WIP: {Your Description}" until it's ready for review. :)

**Comment by XhmikosR** [comment]
Nope it's ready :P

**Comment by haacked** [comment]
Not quite. :) Can't merge it.

**Comment by XhmikosR** [comment]
Is because you keep merging the other PRs and they conflict :)

I'll rebase the branch tomorrow.

**Comment by XhmikosR** [comment]
@Haacked: this can be merged too.

**Pull request merged**
