### PR TITLE
Correct copyright year of LICENSE.md

### PR DESCRIPTION
**Pull request by Jitrixis**
Revert 435a5c4 ; has to be the first year of publication https://en.wikipedia.org/wiki/Copyright#Copyright_notices_in_the_United_States

### CODE REVIEW

**Comment by waldyrious** [comment]
Interesting! This knowledge should be more widespread as the opposite notion appears to be prevalent. :+1:

**Comment by parkr** [comment]
:+1:

**Comment by bkeepers** [comment]
> Interesting! This knowledge should be more widespread as the opposite notion appears to be prevalent.

We have had some internal discussions about recommendations for copyright notices. Since websites and software frequently go through "substantial revisions", which would normally justify noting each year, we have been leaning toward excluding the year entirely.

But, we haven't published any recommendation yet, so we'll revert back to 2013 for now.

**Comment by benbalter** [comment]
Dropping this here, since this discussion inspired a blog post, but I did a deep dive on [copyright notices for open source projects](http://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/) over on my personal site.

**Pull request merged**
