### PR TITLE
Update frontend assets.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
This reminds me, maybe we should switch to html5printshiv instead of the plain one.

**Comment by XhmikosR** [comment]
Bump

**Comment by XhmikosR** [comment]
I guess I should give up.

**Comment by benbalter** [comment]
@XhmikosR it's hard to tell what's going on from the diff. Can you provide a human-readable description? Were there any substantive changes? Also, it looks like at least one fine got un-minified, and some of the paths changed?

**Comment by XhmikosR** [comment]
@benbalter: quite the opposite; everything used is minified. As for the diff, there's no way to do that. Check out the branch locally if you want.

**Comment by strugee** [comment]
> As for the diff, there's no way to do that.

Yes there is. I believe what @benbalter was looking for was something like:

> - Updated JQuery from x.yz to a.bc
> - Added Foolib for some purpose

etc.

**Pull request closed without merging**
