### PR TITLE
Add Open hardware licenses

### PR DESCRIPTION
**Pull request by pimpin**

### CODE REVIEW

**Comment by benbalter** [comment]
@pimpin Thanks for the pull request. Can you provide some rationale for why you think the license should be included?

@skalnik do you happen to know anything about open hardware licensing by chance?

**Comment by skalnik** [comment]
@benbalter Nope, not much other than having heard of them.

**Comment by pimpin** [comment]
@benbalter Your welcome, I admit my PR is a bit dry. :stuck_out_tongue_closed_eyes: 
My current mission takes place in a state agency that cares about "_intangibles_".
In this context, we dig in Open Hardware trend that is al ready present in GH... [look at this project !](https://github.com/aeroseed/urbolienne).

Looking to the site [chooseALicence](http://choosealicense.com/), I thought that those licenses could be shown here.
It might be worth making something aside to separate OHL from current software licenses.

**Comment by strugee** [comment]
We could also link to Open Hardware licenses in a manner similar to how we currently link to Creative Commons.

**Comment by benbalter** [comment]
@pimpin I'd love to merge this given a few minor fixes:
1. The source links seems to 404
2. The formatting (line wraps) seem a bit odd. Where are you getting this from?
3. The smart quotes should be dumb quotes
4. Per https://github.com/github/choosealicense.com/issues/273, can you add `hidden: true` to the YAML front matter?

**Comment by bkeepers** [comment]
Closing this as stale. Let me know if you want to bring it up to date and we can reopen it.

**Pull request closed without merging**
