### PR TITLE
Normalize sorting of license properties

### PR DESCRIPTION
**Pull request by waldyrious**
Properties are now consistently sorted across all license files,
appearing in the following order:

**title**
nickname
tab-slug
redirect_from
category
variant
featured
hidden
**source**

**description**
**how**
note

using

**required**
**permitted**
**forbidden**

### CODE REVIEW

**Comment by benbalter** [comment]
@waldyrious any chance you could add a script to do this automatically? And/Or a test to ensure it stays consistent going forward?

**Comment by waldyrious** [comment]
@benbalter I don't think I have the know-how to do that, but I suppose I can give it a try. Can you give me an example (in this project or elsewhere) of a script or test I could look at to have a starting point?

Then again, I don't think updates to the licenses are expected to be frequent enough to warrant such automation. Am I overlooking something by thinking so?

**Comment by waldyrious** [comment]
@benbalter if I rebase this would you consider merging it? it may not be as optimal as an automated script, but it is an improvement nonetheless, and I have other changes I'd like to submit that depend on this one.

**Comment by benbalter** [comment]
@waldyrious as long as tests pass, would be glad to. Thanks for taking the time to contribute.

**Comment by waldyrious** [comment]
@benbalter done; please check if the rebase worked properly. I also updated the PR description above to match the amended commit message.

**Comment by benbalter** [comment]
Awesome, awesome stuff. Thanks @waldyrious! :game_die: :dancer: :cactus:

**Comment by waldyrious** [comment]
Thanks, @benbalter. Having studied all these licenses and their properties for the purposes of this PR (including choosing a sensible sorting order), I am now proposing  series of changes that IMO would make the metadata cleaner / more robust. See #287, #288, #289, #290 and #291.

**Pull request merged**
