### PR TITLE
Update rules.yml

### PR DESCRIPTION
**Pull request by Tyler887**
Adding the `claims` limitation. Will add to licenses that state it soon.

### CODE REVIEW

**Comment by mlinksva** [comment]
It's not clear to me that this feature rises to level worth cataloging here. What licenses do you have in mind?

**Comment by Tyler887** [comment]
> It's not clear to me that this feature rises to level worth cataloging here. What licenses do you have in mind?

zlib has this limitation, like how most other licenses catalogued on the site do.

**Comment by mlinksva** [comment]
Thanks for explaining. I don't see the benefit of including this. We aren't attempting to do a fine grained description of every license feature. There are other projects that do that such as https://www.osadl.org/Open-Source-License-Checklists.oss-compliance-lists.0.html

**Comment by mlinksva** [comment]
A better link is https://www.osadl.org/Access-to-raw-data.oss-compliance-raw-data-access.0.html

I would be interested in a crosswalk and/or tests to make sure this repo's descriptions of licenses aren't at odds with OSADL's though.

**Pull request closed without merging**
