### PR TITLE
Restore TLDRLegal as "additional resource"

### PR DESCRIPTION
**Pull request by xizhao**
I noticed that TLDRLegal was taken down due to concerns around spam -- we did a big sweep of content in between then and now.

Would be cool to be back on this page, esp given the history of us and ChooseALicense! Feel free to reach out at kevin (at) tldrlegal.com beforehand as well.

### CODE REVIEW

**Comment by waldyrious** [comment]
Kinda tangential, but since we're on the subject: I wish TLDRLegal would become more wiki-like, perhaps with the data being hosted in a github repo or something like that. It could then become a potential good resource for a community-curated list of licenses, aiming at being exhaustive, even listing projects using each license -- see discussion at #377 for context and details.

I'm saying this because a while ago I tried to update the page on the ISC license and had to wait for months for the change to be reviewed. I even offered to help maintain the data / review change requests at the time, but got no answer to that, IIRC. TLDRLegal's potential is great, but such a centralized curation model is neither practical nor aligned with the FOSS ethos.

**Comment by mlinksva** [comment]
@xizhao do you keep spam off the home page? I don't have much confidence with it currently linking to tldrlegal.com/license/hx711_spi which looks like a nonsense entry named for a hardware part and with some C source code as the fulltext. That's not spam I suppose, but could easily be, and is at the least confusing to someone learning about licenses. I'm somewhat embarrassed, and to be a bit hyperbolic, consider it bad internet citizenship, to link to sites featuring spam.

In any case I'll leave this open pending other comments, esp given that I don't know the history between you and ChooseALicense!

**Comment by xizhao** [comment]
@waldyrious That's a good point.  Maybe somewhere in between is to start w/ a more active moderation staff, as right now it's just (me) + summary authors that have the ability to merge changes.  The curation is still decentralized in the sense that account holders of summary submissions have full ability to merge/edit, but if account holders go in-active, it falls to my once-every-few-weeks sweep of things.  Sorry I missed your note -- I just checked my email looking for your username, are you still interested in getting more involved?

@mlinksva That instance doesn't look like spam -- I think maybe a misunderstanding of the "Submit" function (i.e. author wanted to license code under certain terms by putting it on TLDR).  You've got a point though, maybe featuring "newest" submissions on the homepage isn't a great idea and there has to be a level of curation -- the vision of TLDR is more of a self-moderated index and I was imagining this would be a way for newer submissions to get visibility. Do you have any ideas around this?

We have a quality control initiative here: https://tldrlegal.com/verified that tries to distinguish certain types of content w/ a nice "verified" badge.  

RE: history, TLDR began around 2012, and there was some light discussion around collaboration since 2013ish around the inception of ChooseALicense -- I think there was some initial sharing of data and more recently a conversation with @benbalter around Open Sourcing TLDR and moving it to GitHub.  

It's quite an effort and we haven't quite gotten around to it (my fault for lack of time/resources), but I think there's a general consensus that's a direction we want to go.  VCS and merging features of GH are far more powerful/polished than those on TLDR; albeit potentially alienating for non-devs.

**Comment by waldyrious** [comment]
@xizhao I didn't send an email, IIRC -- we chatted a bit over twitter: https://twitter.com/waldyrious/status/579320670254948352. I would love to still help, but my availability is reduced at the moment. In any case, I'd rather participate as any other user in a wiki-like system, than be granted curator privileges in a more centralized workflow. I understand if that isn't immediately possible, but I thought I'd drop the suggestion :)

**Comment by mlinksva** [comment]
> maybe featuring "newest" submissions on the homepage isn't a great idea and there has to be a level of curation

@xizhao exactly. The hx711_spi isn't itself spam, but is a demonstration that there's no barrier to garbage including spam appearing on the home page. If you remove the 'newest' column or filter out stuff from it that has seen zero review I'd be a lot more comfortable pointing people learning about licenses to tldrlegal.

As for open sourcing TLDR, putting the code under and open license and in a public repository is the obvious first step. Just do it. :smile: Using pull requests as a new or the only means of moderating site content is a completely different and I'd bet big project. Which having the code be open source can only help.

**Comment by mlinksva** [comment]
ps @xizhao CI is failing this PR because TLDRLegal's certificate chain is incomplete https://www.ssllabs.com/ssltest/analyze.html?d=tldrlegal.com&latest ... you probably need to concatenate your CA's certificate with the one you installed. Both should have been provided when you obtained the certificate for your domain.

**Comment by kytrinyx** [comment]
@xizhao is there any chance that you'd take "newest" off the homepage?

Before we can merge this, I think that both the issue with "newest" and the certificate chain would need to be resolved.

**Comment by mlinksva** [comment]
Closing for now, @xizhao let us know when the two items @kytrinyx mentions are resolved.

**Pull request closed without merging**
