### PR TITLE
WTFPL

### PR DESCRIPTION
**Pull request by sabas**
Popular license and valid alternative to public domain.
OpenStreetMap editors Potlach2 and iD are two examples of software with this license.

(I'm pulling this for the lulz, I don't think it will be merged :-) )

### CODE REVIEW

**Comment by patosar** [comment]
Oh damn you I just did the same.

**Comment by sabas** [comment]
lol!

**Comment by anaisbetts** [comment]
This license was intentionally left off of the list of choices, because one of the "Whatever you want" things to do, is "Sue the author for liability", which Seems Bad™.  Thanks for submitting it though!

**Comment by sabas** [comment]
Okay, I tried. Thanks to you! :-)

**Comment by benbalter** [comment]
https://github.com/github/choosealicense.com/pull/210 which also implements, is currently open for discussion.

**Pull request closed without merging**
