### PR TITLE
The WTFPL, also a choice

### PR DESCRIPTION
**Pull request by patosar**

### CODE REVIEW

**Comment by jpmckinney** [comment]
@superpatosainz This duplicates #15. Close?

**Comment by anaisbetts** [comment]
Dupe of #15

**Comment by benbalter** [comment]
https://github.com/github/choosealicense.com/pull/210 which also implements, is currently open for discussion.

**Comment by anaisbetts** [comment]
> This license was intentionally left off of the list of choices, because one of the "Whatever you want" things to do, is "Sue the author for liability", which Seems Bad™. Thanks for submitting it though!

Still true ^^  - we shouldn't encourage people to choose licenses that open them up to legal liability

**Comment by benbalter** [comment]
> we shouldn't encourage people to choose licenses that open them up to legal liability

:100:% agree. The idea proposed in https://github.com/github/choosealicense.com/issues/273 (which would need to be resolved before it could be added), would be a class of hidden licenses, that would not be recomended, but, if for example, you come across a WTFPL-licensed project, we could at least provide a google-able page to explain what the use can and can't do (and why they shouldn't choose it for the reasons you mentioned). But again, wouldn't be presented as an option / recomendation anywhere.

**Comment by anaisbetts** [comment]
@benbalter Into it

**Pull request closed without merging**
