### PR TITLE
Update gpl-3.0.txt

### PR DESCRIPTION
**Pull request by nomce**
Changed the sublicense part from forbidden to permitted, according to Wikipedia.

### CODE REVIEW

**Comment by benbalter** [comment]
> according to Wikipedia.

Link?

**Comment by nomce** [comment]
http://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

Sorry, I forgot the link. The third table (section "Article comparison"), column Subliscensing: GPL v2 - no, GPL v3 - yes.

**Comment by nomce** [comment]
So, will you pull this request, please?

**Comment by benbalter** [comment]
Just because something is on wikipedia, that doesn't make it true (especially when a legal interpretation without a cite).

Take a look at [line 209](https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/gpl-3.0.txt#L209) of the license:

> Sublicensing is not allowed; section 10 makes it unnecessary.

**Comment by benbalter** [comment]
Closing as § 10 states:

> 1. Automatic Licensing of Downstream Recipients.
> 
> Each time you convey a covered work, the recipient automatically
> receives a license from the original licensors, to run, modify and
> propagate that work, subject to this License.  You are not responsible
> for enforcing compliance by third parties with this License.

Please reopen if I'm missing something or there's reason to believe otherwise.

**Comment by benbalter** [comment]
Actually I like @bkeepers solution over in https://github.com/github/choosealicense.com/pull/303.

**Pull request closed without merging**
