### PR TITLE
Change copyright date 2004 -> [year] in wtfpl

### PR DESCRIPTION
**Pull request by jacobmischka**
I believe this one is supposed to be the year that the software under the license is published, not the year the license itself was written. But I'm not positive. If I'm wrong please feel free to close!

### CODE REVIEW

**Comment by mlinksva** [comment]
Good catch! But the year is actually right, it's the fill-in fields that are wrong. That part of the license is about the license text itself, see  http://www.wtfpl.net/faq/

**Comment by jacobmischka** [comment]
I believe I fixed the correct one, can you please double check my commit?

**Comment by jacobmischka** [comment]
Oh, you meant their existence is wrong? Hm.

**Comment by jacobmischka** [comment]
Yeah I guess you're right, interesting.

**Comment by mlinksva** [comment]
@jacobmischka Thanks a bunch for noticing this! It's really easy to confuse a copyright notice for the license text itself for a copyright notice for the licensed work, a previous instance in https://github.com/github/choosealicense.com/issues/310

**Pull request merged**
