### PR TITLE
Expose license data as an api

### LINKED ISSUE #40: API
It should have an API for people to hack with :)

For example, just having http://choosealicense.com/licenses/mit.json would be nice.

I would do it, but I don't know if you guys are happy with a Jekyll plugin or not?

:+1:

### PR DESCRIPTION
**Pull request by benbalter**
Exposes all license data as a JSON api. Fixes #40.

Note: Rules are already exposed as http://choosealicense.com/javascripts/annotations.js

Example output:

``` json
[
    {
        "title": "Affero GPL",
        "permalink": "/licenses/agpl/",
        "featured": false,
        "description": "",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.",
        "rules": {
            "required": [
                "include-copyright",
                "document-changes",
                "disclose-source"
            ],
            "permitted": [
                "commercial-use",
                "modifications",
                "distribution"
            ],
            "forbidden": [
                "no-liability",
                "no-sublicense"
            ]
        }
    },
    {
        "title": "Apache v2 License",
        "permalink": "/licenses/apache/",
        "featured": true,
        "description": "A permissive license that also provides an express grant of patent rights from contributors to users.",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.",
        "rules": {
            "required": [
                "include-copyright",
                "document-changes"
            ],
            "permitted": [
                "commercial-use",
                "modifications",
                "distribution",
                "sublicense",
                "patent-grant"
            ],
            "forbidden": [
                "trademark-use",
                "no-liability"
            ]
        }
    },
    {
        "title": "Artistic License 2.0",
        "permalink": "/licenses/artistic/",
        "featured": false,
        "description": "A license that&#8217;s heavily favored by the Perl community.",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace <<year>> with the current year and <<copyright holders>> with the name (or names) of the copyright holders.",
        "rules": {
            "required": [
                "include-copyright",
                "document-changes",
                "disclose-source"
            ],
            "permitted": [
                "commercial-use",
                "modifications",
                "distribution",
                "sublicense",
                "private-use"
            ],
            "forbidden": [
                "no-liability",
                "trademark-use"
            ]
        }
    },
    {
        "title": "BSD (3-Clause) License",
        "permalink": "/licenses/bsd-3-clause/",
        "featured": false,
        "description": "",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace <<year>> with the current year and <<fullname>> with the name (or names) of the copyright holders. Replace {organization} with the organization, if any, that sponsors this work.",
        "rules": {
            "required": [
                "include-copyright"
            ],
            "permitted": [
                "commercial-use",
                "modifications",
                "distribution",
                "sublicense"
            ],
            "forbidden": [
                "no-liability",
                "trademark-use"
            ]
        }
    },
    {
        "title": "BSD 2-Clause license",
        "permalink": "/licenses/bsd/",
        "featured": false,
        "description": "A permissive license that comes in two variants, the <a href=\"/licenses/bsd\">BSD 2-Clause</a> and <a href=\"/licenses/bsd-3-clause\">BSD 3-Clause</a>. Both have very minute differences to the MIT license.",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace <<year>> with the current year and <<fullname>> with the name (or names) of the copyright holders.",
        "rules": {
            "required": [
                "include-copyright"
            ],
            "permitted": [
                "commercial-use",
                "modifications",
                "distribution",
                "sublicense"
            ],
            "forbidden": [
                "no-liability"
            ]
        }
    },
    {
        "title": "Eclipse Public License v1.0",
        "permalink": "/licenses/eclipse/",
        "featured": false,
        "description": "Used by the Eclipse foundation for its software, this license includes reciprocal requirements in some cases.",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.",
        "rules": {
            "required": [
                "disclose-source",
                "include-copyright"
            ],
            "permitted": [
                "commercial-use",
                "distribution",
                "modifications",
                "sublicense",
                "patent-grant"
            ],
            "forbidden": [
                "no-liability"
            ]
        }
    },
    {
        "title": "GPL v2",
        "permalink": "/licenses/gpl-v2/",
        "featured": true,
        "description": "",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.",
        "rules": {
            "required": [
                "include-copyright",
                "document-changes",
                "disclose-source"
            ],
            "permitted": [
                "commercial-use",
                "modifications",
                "distribution",
                "patent-grant"
            ],
            "forbidden": [
                "no-liability",
                "no-sublicense"
            ]
        }
    },
    {
        "title": "GPL v3",
        "permalink": "/licenses/gpl-v3/",
        "featured": false,
        "description": "GPL is the most widely used free software license and has a strong copyleft requirement. When distributing derived works, the source code of the work must be made available under the same license.",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.",
        "rules": {
            "required": [
                "include-copyright",
                "document-changes",
                "disclose-source"
            ],
            "permitted": [
                "commercial-use",
                "modifications",
                "distribution",
                "patent-grant"
            ],
            "forbidden": [
                "no-liability",
                "no-sublicense"
            ]
        }
    },
    {
        "title": "LGPL v2.1",
        "permalink": "/licenses/lgpl-v2.1/",
        "featured": false,
        "description": "Primarily used for software libraries, LGPL requires that derived works be licensed under the same license, but works that only link to it do not fall under this restriction.",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.",
        "rules": {
            "required": [
                "include-copyright",
                "library-usage",
                "disclose-source"
            ],
            "permitted": [
                "commercial-use",
                "modifications",
                "distribution",
                "sublicense",
                "patent-grant"
            ],
            "forbidden": [
                "no-liability"
            ]
        }
    },
    {
        "title": "LGPL v3",
        "permalink": "/licenses/lgpl-v3/",
        "featured": false,
        "description": "Version 3 of the LGPL is an additional set of permissions to the <a href=\"/licenses/gpl-v3\">GPL v3 license</a> that requires that derived works be licensed under the same license, but works that only link to it do not fall under this restriction.",
        "how": "This license is an additional set of permissions to the <a href=\"/licenses/gpl-v3\">GPL v3</a> license. Follow the instructions to apply the GPL v3 license. Then either paste this text to the bottom of that file OR add a separate file (typically named COPYING.lesser or LICENSE.lesser) in the root of your source code and copy the text.",
        "rules": {
            "required": [
                "include-copyright",
                "library-usage",
                "disclose-source"
            ],
            "permitted": [
                "commercial-use",
                "modifications",
                "distribution",
                "sublicense",
                "patent-grant"
            ],
            "forbidden": [
                "no-liability"
            ]
        }
    },
    {
        "title": "MIT License",
        "permalink": "/licenses/mit/",
        "featured": true,
        "description": "A permissive license that is short and to the point. It lets people do anything with your code with proper attribution and without warranty.",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace <<year>> with the current year and <<fullname>> with the name (or names) of the copyright holders.",
        "rules": {
            "required": [
                "include-copyright"
            ],
            "permitted": [
                "commercial-use",
                "modifications",
                "distribution",
                "sublicense"
            ],
            "forbidden": [
                "no-liability"
            ]
        }
    },
    {
        "title": "Mozilla Public License Version 2.0",
        "permalink": "/licenses/mozilla/",
        "featured": false,
        "description": "The Mozilla Public License (MPL 2.0) is maintained by the Mozilla foundation. This license attempts to be a compromise between the permissive BSD license and the reciprocal GPL license.",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.",
        "rules": {
            "required": [
                "disclose-source",
                "include-copyright"
            ],
            "permitted": [
                "commercial-use",
                "modifications",
                "distribution",
                "sublicense",
                "patent-grant"
            ],
            "forbidden": [
                "no-liability",
                "trademark-use"
            ]
        }
    },
    {
        "title": "No License",
        "permalink": "/licenses/no-license/",
        "featured": false,
        "description": "You retain all rights and do not permit distribution, reproduction, or derivative works. You may grant some rights in cases where you publish your source code to a site that requires accepting terms of service. For example, publishing to GitHub requires you allow others to view and fork your code.",
        "how": "Simply do nothing, though including a copyright notice is recommended.",
        "rules": {
            "required": [
                "include-copyright"
            ],
            "permitted": [
                "private-use",
                "commercial-use"
            ],
            "forbidden": [
                "modifications",
                "distribution",
                "sublicense"
            ]
        }
    },
    {
        "title": "Public Domain (CC0)",
        "permalink": "/licenses/public-domain/",
        "featured": false,
        "description": "Because copyright attaches automatically in many countries, the Creative Commons CC0 License is recommended to ensure that your work is available everywhere under terms that most closely follow the spirit of a public domain work.",
        "how": "Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. You can alternatively use the <a href=\"http://creativecommons.org/choose/zero/\">Creative Commons CC0 tool</a> to generate HTML with embedded metadata to mark your work as CC0.",
        "rules": {
            "required": [],
            "permitted": [
                "private-use",
                "commercial-use",
                "modifications",
                "distribution",
                "sublicense"
            ],
            "forbidden": [
                "no-liability"
            ]
        }
    }
]
```

### CODE REVIEW

**Comment by haacked** [comment]
Jekyll is killer. :sparkles: Will GitHub pages expose this with the proper mime type `application/json`?

**Comment by benbalter** [comment]
> Will GitHub pages expose this with the proper mime type `application/json`?

Yuuuppp.

[Example](http://ben.balter.com/tags.json):

``` http
HTTP/1.1 200 OK
Content-Length: 94327
Server: GitHub.com
Date: Tue, 16 Jul 2013 16:02:00 GMT
Content-Type: application/json
Last-Modified: Fri, 12 Jul 2013 15:21:56 GMT
Connection: close
Expires: Tue, 16 Jul 2013 16:12:00 GMT
Cache-Control: max-age=600
Vary: Accept-Encoding
Accept-Ranges: bytes
```

**Comment by cobyism** [comment]
:metal:

**Comment by haacked** [comment]
amazeballs! :space_invader:

**Pull request merged**
