### PR TITLE
Update the year of copyright to 2014

### PR DESCRIPTION
**Pull request by shinnn**
If `2013 - 2014` is preferred, I'll fix this PR.

### CODE REVIEW

**Comment by haacked** [comment]
Thanks!

**Comment by tekkub** [comment]
If you went with `{{ site.time | date: "%Y" }}` it will always be up to date as of the last deployment.

**Comment by tekkub** [comment]
Oh derp, this is for the license for this repo, not the value displayed on the site.

**Comment by afeld** [comment]
Ha, this a good meta-issue... when including licenses, I have no idea if I'm supposed to include the year range that the project has been active, or just the current year.

/cc @talniv

**Pull request merged**
