### PR TITLE
application.css: Minor cleanup.

### PR DESCRIPTION
**Pull request by XhmikosR**
Move the common `color` property along with the other common properties and remove inherited properties.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@Haacked: Thanks.

I have a of question...
How is the order in /licenses determined? On my local dev environment I have an order by name but in http://choosealicense.com/licenses/ I see a different order.

Check the images...

**Comment by XhmikosR** [comment]
Oh and another thing, I was wondering why `.triptych h3` has a width of 220px. Doesn't it make sense for it to have the width of its parent element, `.triptych li` which is 280px?

**Comment by haacked** [comment]
I honestly don't know what controls the sort. We should probably update it to make it explicit. As for `.triptych` width, i defer to @jasonlong

**Comment by XhmikosR** [comment]
OK, I will wait for others feedback. Maybe @afeld has an opinion about the above too.

**Comment by afeld** [comment]
> Oh and another thing, I was wondering why `.triptych h3` has a width of 220px. Doesn't it make sense for it to have the width of its parent element, `.triptych li` which is 280px?

No, I imagine the thinking was that the title shouldn't stretch the full with of the text below it.

choosing_an_oss_license_doesnt_need_to_be_scary_-_choosealicense_com-4

**Comment by XhmikosR** [comment]
I noticed that too, but how about just using padding and removing the width from h3? Not that currently the website is responsive but you know, fixed width isn't very flexible :)

**Comment by afeld** [comment]
Yep, that would work.  Just seems like yak shaving at this point.

**Comment by XhmikosR** [comment]
Had to look urban dictionary for "yak shaving" :P 

Are there any plans to make the site fully responsive? If so I could try using Bootstrap 3.x and see how it goes.

**Comment by afeld** [comment]
Not a big priority for us, but happy to discuss in a separate issue/PR :thumbsup:

**Comment by jasonlong** [comment]
IIRC, the narrower title width was to prevent some odd [orphan](http://opusdesign.us/typographic-widows-orphans/) situations. The padding method would work as well.

**Comment by haacked** [comment]
IMHO that is not an example of "yak shaving". :stuck_out_tongue:

**Comment by haacked** [comment]
I should clarify, yak shaving is things that are necessary to enable another thing to get done. The padding isn't necessary. THIS, is yak shaving. :smile:

**Comment by haacked** [comment]
Ack! Image is too big. http://d3j5vwomefv46c.cloudfront.net/photos/large/795272903.gif?1375176386

**Comment by haacked** [comment]
BTW, it's not "necessary", but I'm not opposed to the polish.

**Comment by XhmikosR** [comment]
A fully responsive website is something I'd like to see so I might experiment with it in the near future. :)

**Comment by jasonlong** [comment]
@XhmikosR That would definitely be cool. Feel free to take a stab at it.

**Comment by afeld** [comment]
@XhmikosR If you (or someone) takes a stab at it, feel free to take it one page at a time, so that it's a handful of more more digestible PRs.

**Comment by XhmikosR** [comment]
@afeld not sure if that's possible but I will try to make the patches clear enough. But I don't promise anything yet :P

**Comment by afeld** [comment]
Whatever's easiest!

**Comment by mjastrzebowski** [comment]
I'd love to make this website responsive as my first contribution :)

**Comment by XhmikosR** [comment]
@mjastrzebowski: I haven't started working on this yet, but my plan was to experiment with Bootstrap 3.x.
If you think you'll get to it sooner than me, which is what I expect since I have many projects in my plate, please go ahead and make a PR. :+1:

**Comment by afeld** [comment]
Feel free to make a separate issue to track progress.

**Pull request merged**
