### PR TITLE
format 'using' property as a bulleted list (fixes #292)

### LINKED ISSUE #292: "using" property should be formatted as a bulleted list, like "required" et. al
For consistency, and to prevent whitespace changes by text editors.

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by waldyrious** [comment]
Not sure how to fix the Travis failure. Any help appreciated.

**Comment by waldyrious** [comment]
Oh crap. I forgot to update my fork's gh-pages prior to doing this. Sorry for the noise, will rebase.

**Comment by waldyrious** [comment]
Huh. Same error. Not sure why this failure doesn't show up on Travis' testing of the current gh-pages. @bkeepers, @benbalter what should I do?

**Comment by bkeepers** [comment]
The [template that uses this data](https://github.com/github/choosealicense.com/blob/5feefc222c6a7aa3badb7d59df665d460192cb80/_includes/sidebar.html#L49-L51) needs to be updated:

```
      {% for using in page.using %}
        <li><a href="{{ using[1] }}" target="_blank">{{ using[0] }}</a></li>
      {% endfor %}
```

I'm not actually sure how to update this with the new format.

**Comment by benbalter** [comment]
It's not super elegant, but this seems to work with the new data structure:

``` liquid
{% for using in page.using %}
  {% for hash in using %}
    <li><a href="{{ hash[1] }}" target="_blank">{{ hash[0] }}</a></li>
  {% endfor %}
{% endfor %}
```

**Comment by waldyrious** [comment]
@benbalter @bkeepers ping?

**Comment by bkeepers** [comment]
Looks good, thanks!

**Pull request merged**
