### PR TITLE
Add "BSD 2-Clause + Patent" license

### PR DESCRIPTION
**Pull request by ArniDagur**
I would totally use this license for all of my projects if it was recognized by GitHub. It is OSI approved and provides a patent grant similar (equivilent?) to the Apache-2.0 license. It is the best of what the MIT and Apache-2.0 licenses have to offer.

This license should not be confused with the whole Facebook–React license debacle (https://github.com/facebook/react/commit/dcf415c2b91ce52fd5d4dd02b70875ba9d33290f). In that case, Facebook licensed React under the classic BSD 2-Clause license but included a patent grant in a seperate PATENTS file which had a termination clause written in a rather problematic manner.

A [Github code search](https://github.com/search?q=BSD+%2B+Patent+filename%3ALICENSE&type=Code) reveals a lot of hits, but I'm sceptical that they are all for this license. I would also be interested to see how many projects use the BSD 2-Clause license in addition to a seperate patent grant in a PATENTS file, as these are the projects that would benefit the most from this license.

### CODE REVIEW

**Comment by mlinksva** [comment]
It looks to me like it's used very rarely -- https://github.com/search?q=%22non-copyrightable+additions%22+path%3A**%2FLICENSE*&type=code has 17 results (the quoted string seems to be unique to this license).

Happy to add when it meets our [criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license).

**Comment by mlinksva** [comment]
By the way @ArniDagur thanks for suggesting this, sorry it isn't widely used enough yet. Regarding

> provides a patent grant similar (equivilent?) to the Apache-2.0 license. It is the best of what the MIT and Apache-2.0 licenses have to offer.

There is one big difference regarding termination of the patent grant, which you may or may not care about.

Another recent similar (relatively simple permissive license with an express patent grant) that is cataloged here: [UPL-1.0](https://choosealicense.com/licenses/upl-1.0/).

**Comment by ahmad380360** [comment]
شكرا

**Comment by NurrSabbir** [comment]
> would totally use this license for all of my projects if it was recognized by GitHub. It is OSI approved and provides a patent grant similar (equivilent?) to the Apache-2.0 license. It is the best of what the MIT and Apache-2.0 licenses have to offer.
> 
> This license should not be confused with the whole Facebook–React license debacle ([facebook/react@dcf415c](https://github.com/facebook/react/commit/dcf415c2b91ce52fd5d4dd02b70875ba9d33290f)). In that case, Facebook licensed React under the classic BSD 2-Clause license but included a patent grant in a seperate PATENTS file which had a termination clause written in a rather problematic manner.
> 
> A [Github code search](https://github.com/search?q=BSD+%2B+Patent+filename%3ALICENSE&type=Code) reveals a lot of hits, but I'm sceptical that they are all for this license. I would also be interested to see how many projects use the BSD 2-Clause license in addition to a seperate patent grant in a PATENTS file, as these are the projects that would benefit the most from this license.

Your contribution will be used to improve translation quality and may be shown to users anonymously

**Comment by istx25** [comment]
Please merge this license!

**Comment by mlinksva** [comment]
@non-binary feel free to help by suggesting example uses per https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license ... currently this PR provides none. See other licenses in `_licenses` to see how examples are provided for other licenses.

I suspect this one is well below the fuzzy threshold of use required for cataloging there, but concrete examples would be one path to changing this suspicion. :smile:

**Comment by istx25** [comment]
@mlinksva This is a suitable license for https://github.com/non-binary/enigma (and many other projects) but without GitHub supporting this license, and breaking it down for them, and showing people they can trust it, it brings legal barriers users would face by us using a "custom license". Projects with custom licenses immediately have to deal with potential users being suspicious because it isn't a license GitHub breaks down for them/basically says they can trust.

Enigma is released under the Apache 2.0 license. We chose to use this license because of the protections it provides to our project contributors (specifically the express grant of patent rights). Which the BSD+Patent license would provide however, since for the reasons above, we use Apache. I don't want to use the Apache license because by using the Apache license, we're and everyone who uses the Apache license complicit in cultural appropriation. Indigenous cultures and peoples should not be used as a dictionary to name non-Indigenous projects or licenses. 

Please merge the license so more projects can use it without being written off because of the license being unknown to them and having to contact their legal team.

**Comment by mlinksva** [comment]
@non-binary thanks for explaining. Interesting ordering! I'm curious why UPL-1.0 isn't a good option -- it includes an express grant of patent rights, and has a non-appropriative name (and a name that does not pay homage to a slave owner, unlike any of the BSDs).

**Comment by istx25** [comment]
@mlinksva It is a good alternative, however still stands that I'm sure many people haven't heard of UPL vs basically everyone I know has heard of the BSD licenses and would be more comfortable seeing a BSD license with a patent grant vs a license they've never heard of. With that said though, I am considering switching to UPL if this doesn't get merged.

**Review by MHRANN — APPROVED** [review]
mhrann

**Comment by dropwhile** [comment]
This license is [listed by BlueOak][1] as “gold”. Also [here][4]. 
* It has an [spdx designation][2].   
* Seems to [have usage][3]. 
* [Approved by the FSF as GPL compatible][5]?  
* [OSI approved][6]?  
* Notable repos:
  * 2.4K stars - https://github.com/tianocore/edk2/blob/master/License.txt


I would love to be able to have its use parsed, so I could more easily use it. 

[1]: https://blueoakcouncil.org/list
[2]: https://spdx.org/licenses/BSD-2-Clause-Patent.html
[3]: https://github.com/search?q=BSD-2-Clause-Patent&type=code
[4]: https://writing.kemitchell.com/2019/11/07/BSD-Patents.html
[5]: https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2017-March/002989.html
[6]: https://opensource.org/licenses/BSDplusPatent

**Review by MrRawes — CHANGES_REQUESTED** [review]
IMO the "source" should be the [spdx url](https://spdx.org/licenses/BSD-2-Clause-Patent.html)

**Comment by JoshuaKimsey** [comment]
I thought I should add here that the total number of users of the BSD 2-Clause+Patent is ~100 now, but it's being used by some pretty large projects, including some by [Netflix](https://github.com/Netflix/vmaf) and some others too.

**Comment by mlinksva** [comment]
@MrRawes thanks. Yes source was removed everywhere in #601 because it is redundant with SPDX and this couldn't have been merged without also removing it.

@JoshuaKimsey thanks for the update/ping. Unfortunately https://github.com/Netflix/vmaf/blob/master/LICENSE is not a usable example as it has a bunch of added stuff in the beginning. Any suggestions of projects with unmodified (except for (c) holder) license texts?

**Pull request merged**
