### PR TITLE
CSS cleanup

### PR DESCRIPTION
**Pull request by XhmikosR**
Second attempt... I split the changes so that they can be reviewed more easily.

About the unicode character. I know it doesn't break anything, but on the other hand it doesn't provide any gain.

About the shorthand properties, they exist for this specific reason; to combine all properties without bloating the css.

Anyway, I'm open to feedback, as usual.

### CODE REVIEW

**Comment by haacked** [comment]
I like these changes! My only concern is that you got rid of the fallback font families. Is that safe? For example, could that negatively affect mobile devices that might not have support for font embedding? I'm guessing by now, it should be just fine.

If you tested these changes, then I'm all for them. /cc @jasonlong

**Comment by XhmikosR** [comment]
@Haacked: fonts are inherited which means you do not need to specify them in every selector...

**Comment by XhmikosR** [comment]
@Haacked: I went with a slightly better approach; I grouped together common header properties.

**Comment by haacked** [comment]
:cool:

**Comment by XhmikosR** [comment]
Thanks!

Now the only real issue is the Firefox copied to clipboard text not showing up...

**Comment by XhmikosR** [comment]
@Haacked: BTW, do you still still support IE 6 and 7? If not we could/should remove the star hacks used in the css.

**Comment by haacked** [comment]
I'll look at the stats tomorrow. I have no idea what kind of traffic we get from those browsers.

**Pull request merged**
