### PR TITLE
Use `innerText` if `textContent` isn't available.

### PR DESCRIPTION
**Pull request by XhmikosR**
This should cover all cases.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Alternatively, we could use jQuery's `html()` which should also work in all browsers.

I have pushed both solutions; I'll wait for feedback in order to rebase and remove one of the two.

Note that I have tested this with IE 9+, Chrome and Firefox work fine. IE 8 doesn't work, but doesn't work in current gh-pages either.

/CC @afeld @gjtorikian

**Comment by XhmikosR** [comment]
So, any thoughts?

**Comment by benbalter** [comment]
@XhmikosR is there an issue that this fixes? If not, could you provide some more context? Is there an advantage to one approach over the other?

**Comment by XhmikosR** [comment]
Have a look to `innerText and`textContent` and you will see that there are cases one is missing. The jQuery solution should work everywhere.

Note, that I haven't looked at this patch for months, so no idea what happens now.

**Pull request closed without merging**
