### PR TITLE
sort license properties as permissions > conditions > limitations (fixes #387)

### LINKED ISSUE #387: Reorder rules in license pages and elsewhere to match the sequence permissions/conditions/limitations
I'm planning on submitting a PR doing this as soon as #386 is settled.

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by mlinksva** [comment]
I guess this is toward fixing #387. Do you want to reorder any other licenses needing it in this PR also? Fine if not, just thought I'd mention as it doesn't seem necessary to consider them one by one. Thanks!

**Comment by waldyrious** [comment]
Argh! I had that one so deep in the backburner it slipped under my radar! I'll make the same change in the other licenses as well, sure.

**Comment by waldyrious** [comment]
@mlinksva updated the PR with the remaining changes, rebased, force-pushed and edited the PR title. Travis failure is unrelated:

```
- ./_site/licenses/cc-by-sa-4.0/index.html
  *  External link https://creativecommons.org/compatiblelicenses/ failed: 503 No error
rake aborted!
HTML-Proofer found 1 failure!
```

**Comment by mlinksva** [comment]
Thanks!

**Pull request merged**
