### PR TITLE
Use CC0-1.0 license text from source

### LINKED ISSUE #518: CC0 license differs from the official one
* https://choosealicense.com/licenses/cc0-1.0/
vs
* https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt

<br>

Diff: https://www.diffchecker.com/4rG1VpXM

<details><summary>click to expand</summary>

```diff
0a1,2
> Creative Commons Legal Code
> 
2a5,13
>     CREATIVE COMMONS CORPORATION IS NOT A LAW FIRM AND DOES NOT PROVIDE
>     LEGAL SERVICES. DISTRIBUTION OF THIS DOCUMENT DOES NOT CREATE AN
>     ATTORNEY-CLIENT RELATIONSHIP. CREATIVE COMMONS PROVIDES THIS
>     INFORMATION ON AN "AS-IS" BASIS. CREATIVE COMMONS MAKES NO WARRANTIES
>     REGARDING THE USE OF THIS DOCUMENT OR THE INFORMATION OR WORKS
>     PROVIDED HEREUNDER, AND DISCLAIMS LIABILITY FOR DAMAGES RESULTING FROM
>     THE USE OF THIS DOCUMENT OR THE INFORMATION OR WORKS PROVIDED
>     HEREUNDER.
> 
6,7c17,18
< exclusive Copyright and Related Rights (defined below) upon the creator and
< subsequent owner(s) (each and all, an "owner") of an original work of
---
> exclusive Copyright and Related Rights (defined below) upon the creator
> and subsequent owner(s) (each and all, an "owner") of an original work of
10,19c21,30
< Certain owners wish to permanently relinquish those rights to a Work for the
< purpose of contributing to a commons of creative, cultural and scientific
< works ("Commons") that the public can reliably and without fear of later
< claims of infringement build upon, modify, incorporate in other works, reuse
< and redistribute as freely as possible in any form whatsoever and for any
< purposes, including without limitation commercial purposes. These owners may
< contribute to the Commons to promote the ideal of a free culture and the
< further production of creative, cultural and scientific works, or to gain
< reputation or greater distribution for their Work in part through the use and
< efforts of others.
---
> Certain owners wish to permanently relinquish those rights to a Work for
> the purpose of contributing to a commons of creative, cultural and
> scientific works ("Commons") that the public can reliably and without fear
> of later claims of infringement build upon, modify, incorporate in other
> works, reuse and redistribute as freely as possible in any form whatsoever
> and for any purposes, including without limitation commercial purposes.
> These owners may contribute to the Commons to promote the ideal of a free
> culture and the further production of creative, cultural and scientific
> works, or to gain reputation or greater distribution for their Work in
> part through the use and efforts of others.
21,27c32,38
< For these and/or other purposes and motivations, and without any expectation
< of additional consideration or compensation, the person associating CC0 with a
< Work (the "Affirmer"), to the extent that he or she is an owner of Copyright
< and Related Rights in the Work, voluntarily elects to apply CC0 to the Work
< and publicly distribute the Work under its terms, with knowledge of his or her
< Copyright and Related Rights in the Work and the meaning and intended legal
< effect of CC0 on those rights.
---
> For these and/or other purposes and motivations, and without any
> expectation of additional consideration or compensation, the person
> associating CC0 with a Work (the "Affirmer"), to the extent that he or she
> is an owner of Copyright and Related Rights in the Work, voluntarily
> elects to apply CC0 to the Work and publicly distribute the Work under its
> terms, with knowledge of his or her Copyright and Related Rights in the
> Work and the meaning and intended legal effect of CC0 on those rights.
31,32c42,43
< Related Rights"). Copyright and Related Rights include, but are not limited
< to, the following:
---
> Related Rights"). Copyright and Related Rights include, but are not
> limited to, the following:
34,35c45,61
<   i. the right to reproduce, adapt, distribute, perform, display, communicate,
<   and translate a Work;
---
>   i. the right to reproduce, adapt, distribute, perform, display,
>      communicate, and translate a Work;
>  ii. moral rights retained by the original author(s) and/or performer(s);
> iii. publicity and privacy rights pertaining to a person's image or
>      likeness depicted in a Work;
>  iv. rights protecting against unfair competition in regards to a Work,
>      subject to the limitations in paragraph 4(a), below;
>   v. rights protecting the extraction, dissemination, use and reuse of data
>      in a Work;
>  vi. database rights (such as those arising under Directive 96/9/EC of the
>      European Parliament and of the Council of 11 March 1996 on the legal
>      protection of databases, and under any national implementation
>      thereof, including any amended or successor version of such
>      directive); and
> vii. other similar, equivalent or corresponding rights throughout the
>      world based on applicable law or treaty, and any national
>      implementations thereof.
37c63,78
<   ii. moral rights retained by the original author(s) and/or performer(s);
---
> 2. Waiver. To the greatest extent permitted by, but not in contravention
> of, applicable law, Affirmer hereby overtly, fully, permanently,
> irrevocably and unconditionally waives, abandons, and surrenders all of
> Affirmer's Copyright and Related Rights and associated claims and causes
> of action, whether now known or unknown (including existing as well as
> future claims and causes of action), in the Work (i) in all territories
> worldwide, (ii) for the maximum duration provided by applicable law or
> treaty (including future time extensions), (iii) in any current or future
> medium and for any number of copies, and (iv) for any purpose whatsoever,
> including without limitation commercial, advertising or promotional
> purposes (the "Waiver"). Affirmer makes the Waiver for the benefit of each
> member of the public at large and to the detriment of Affirmer's heirs and
> successors, fully intending that such Waiver shall not be subject to
> revocation, rescission, cancellation, termination, or any other legal or
> equitable action to disrupt the quiet enjoyment of the Work by the public
> as contemplated by Affirmer's express Statement of Purpose.
39,43c80,100
<   iii. publicity and privacy rights pertaining to a person's image or likeness
<   depicted in a Work;
< 
<   iv. rights protecting against unfair competition in regards to a Work,
<   subject to the limitations in paragraph 4(a), below;
---
> 3. Public License Fallback. Should any part of the Waiver for any reason
> be judged legally invalid or ineffective under applicable law, then the
> Waiver shall be preserved to the maximum extent permitted taking into
> account Affirmer's express Statement of Purpose. In addition, to the
> extent the Waiver is so judged Affirmer hereby grants to each affected
> person a royalty-free, non transferable, non sublicensable, non exclusive,
> irrevocable and unconditional license to exercise Affirmer's Copyright and
> Related Rights in the Work (i) in all territories worldwide, (ii) for the
> maximum duration provided by applicable law or treaty (including future
> time extensions), (iii) in any current or future medium and for any number
> of copies, and (iv) for any purpose whatsoever, including without
> limitation commercial, advertising or promotional purposes (the
> "License"). The License shall be deemed effective as of the date CC0 was
> applied by Affirmer to the Work. Should any part of the License for any
> reason be judged legally invalid or ineffective under applicable law, such
> partial invalidity or ineffectiveness shall not invalidate the remainder
> of the License, and in such case Affirmer hereby affirms that he or she
> will not (i) exercise any of his or her remaining Copyright and Related
> Rights in the Work or (ii) assert any associated claims and causes of
> action with respect to the Work, in either case contrary to Affirmer's
> express Statement of Purpose.
45,92d101
<   v. rights protecting the extraction, dissemination, use and reuse of data in
<   a Work;
< 
<   vi. database rights (such as those arising under Directive 96/9/EC of the
<   European Parliament and of the Council of 11 March 1996 on the legal
<   protection of databases, and under any national implementation thereof,
<   including any amended or successor version of such directive); and
< 
<   vii. other similar, equivalent or corresponding rights throughout the world
<   based on applicable law or treaty, and any national implementations thereof.
< 
< 2. Waiver. To the greatest extent permitted by, but not in contravention of,
< applicable law, Affirmer hereby overtly, fully, permanently, irrevocably and
< unconditionally waives, abandons, and surrenders all of Affirmer's Copyright
< and Related Rights and associated claims and causes of action, whether now
< known or unknown (including existing as well as future claims and causes of
< action), in the Work (i) in all territories worldwide, (ii) for the maximum
< duration provided by applicable law or treaty (including future time
< extensions), (iii) in any current or future medium and for any number of
< copies, and (iv) for any purpose whatsoever, including without limitation
< commercial, advertising or promotional purposes (the "Waiver"). Affirmer makes
< the Waiver for the benefit of each member of the public at large and to the
< detriment of Affirmer's heirs and successors, fully intending that such Waiver
< shall not be subject to revocation, rescission, cancellation, termination, or
< any other legal or equitable action to disrupt the quiet enjoyment of the Work
< by the public as contemplated by Affirmer's express Statement of Purpose.
< 
< 3. Public License Fallback. Should any part of the Waiver for any reason be
< judged legally invalid or ineffective under applicable law, then the Waiver
< shall be preserved to the maximum extent permitted taking into account
< Affirmer's express Statement of Purpose. In addition, to the extent the Waiver
< is so judged Affirmer hereby grants to each affected person a royalty-free,
< non transferable, non sublicensable, non exclusive, irrevocable and
< unconditional license to exercise Affirmer's Copyright and Related Rights in
< the Work (i) in all territories worldwide, (ii) for the maximum duration
< provided by applicable law or treaty (including future time extensions), (iii)
< in any current or future medium and for any number of copies, and (iv) for any
< purpose whatsoever, including without limitation commercial, advertising or
< promotional purposes (the "License"). The License shall be deemed effective as
< of the date CC0 was applied by Affirmer to the Work. Should any part of the
< License for any reason be judged legally invalid or ineffective under
< applicable law, such partial invalidity or ineffectiveness shall not
< invalidate the remainder of the License, and in such case Affirmer hereby
< affirms that he or she will not (i) exercise any of his or her remaining
< Copyright and Related Rights in the Work or (ii) assert any associated claims
< and causes of action with respect to the Work, in either case contrary to
< Affirmer's express Statement of Purpose.
< 
95,116c104,121
<   a. No trademark or patent rights held by Affirmer are waived, abandoned,
<   surrendered, licensed or otherwise affected by this document.
< 
<   b. Affirmer offers the Work as-is and makes no representations or warranties
<   of any kind concerning the Work, express, implied, statutory or otherwise,
<   including without limitation warranties of title, merchantability, fitness
<   for a particular purpose, non infringement, or the absence of latent or
<   other defects, accuracy, or the present or absence of errors, whether or not
<   discoverable, all to the greatest extent permissible under applicable law.
< 
<   c. Affirmer disclaims responsibility for clearing rights of other persons
<   that may apply to the Work or any use thereof, including without limitation
<   any person's Copyright and Related Rights in the Work. Further, Affirmer
<   disclaims responsibility for obtaining any necessary consents, permissions
<   or other rights required for any use of the Work.
< 
<   d. Affirmer understands and acknowledges that Creative Commons is not a
<   party to this document and has no duty or obligation with respect to this
<   CC0 or use of the Work.
< 
< For more information, please see
< <http://creativecommons.org/publicdomain/zero/1.0/>
---
>  a. No trademark or patent rights held by Affirmer are waived, abandoned,
>     surrendered, licensed or otherwise affected by this document.
>  b. Affirmer offers the Work as-is and makes no representations or
>     warranties of any kind concerning the Work, express, implied,
>     statutory or otherwise, including without limitation warranties of
>     title, merchantability, fitness for a particular purpose, non
>     infringement, or the absence of latent or other defects, accuracy, or
>     the present or absence of errors, whether or not discoverable, all to
>     the greatest extent permissible under applicable law.
>  c. Affirmer disclaims responsibility for clearing rights of other persons
>     that may apply to the Work or any use thereof, including without
>     limitation any person's Copyright and Related Rights in the Work.
>     Further, Affirmer disclaims responsibility for obtaining any necessary
>     consents, permissions or other rights required for any use of the
>     Work.
>  d. Affirmer understands and acknowledges that Creative Commons is not a
>     party to this document and has no duty or obligation with respect to
>     this CC0 or use of the Work.
```

</details>

### PR DESCRIPTION
**Pull request by mlinksva**
The existing license text was introduced in https://github.com/github/choosealicense.com/pull/126 presumably by copying and pasting from https://creativecommons.org/publicdomain/zero/1.0/legalcode though I'm not sure how to explain the link at the end. Probably should be updated with https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt or https://spdx.org/licenses/CC0-1.0.html ... latter marks disclaimer as optional and doesn't have first line "Creative Commons Legal Code". This commit uses former.

Making due to https://github.com/benbalter/licensee/issues/172 but holding off on merge pending more discussion there.

Fixes #518

### CODE REVIEW

**Review by benbalter — APPROVED** [review]

**Comment by benbalter** [comment]
Just making a note, when we update Licensee with this license, we'll want to test that it matches with and without the disclaimer to support existing licenses that were created with the old template.

**Comment by mlinksva** [comment]
I've been holding off on merging this pending https://github.com/spdx/license-list/issues/5 to make sure that we all settle on the same text. I went ahead and opened a couple PRs to their working repo over the last few days to hopefully get resolution sooner.

**Comment by winksaville** [comment]
AFAICT the [cc0.txt on the github license-templates](https://github.com/licenses/license-templates/blob/master/templates/cc0.txt) has the official legalcode.txt. In anycase, I believe both the template and choosealicense should match.

**Comment by wking** [comment]
> I've been holding off on merging this pending spdx/license-list#5 to make sure that we all settle on the same text.

I believe this was addressed by spdx/license-list-XML#487, but I've filed spdx/license-list-XML#608 just now to be sure ;).

**Comment by mlinksva** [comment]
Just to mention for anyone only following this issue, I'm now holding off merging it pending https://github.com/benbalter/licensee/pull/253#issuecomment-361781804 or another solution to detect both CC0-1.0 license texts is settled on for licensee.

**Comment by bradleeedmondson** [comment]
Thanks @mlinksva. 

Partially addressed (as far as scanning existing repos goes) in SPDX template by spdx/license-list-XML#489, but this should still be fixed here so we stop people spawning new repos with non-canonical text when they intend to use CC0-1.0.

**Comment by clarkmoody** [comment]
It seems everyone is waiting on someone else. Can we get some forward motion here?

**Comment by mlinksva** [comment]
The current status is still what I wrote nearly 10 months ago:

> I'm now holding off merging it pending benbalter/licensee#253 (comment) or another solution to detect both CC0-1.0 license texts is settled on for licensee.

I think @benbalter does have another solution in mind for licensee to be able to detect both versions of the CC0-1.0 text, extending other work he's been doing on licensee recently.  I'm happy to merge this anytime, but don't want to inadvertently break licensee detection of CC0-1.0 for most of the repos intending to use that license on GitHub. @benbalter any recommendation, or correction if I'm missing something?

**Comment by ghost** [comment]
Duplicate of #

**Review by benbalter — APPROVED** [review]

**Comment by mlinksva** [comment]
Tests will pass on this PR when a new version of licensee has been released (due to the examples added in #699 which match the 2013-2019 choosealicense text, but not this one...the new licensee version will match both).

**Comment by mlinksva** [comment]
The tests pass now given @alistair23's good [idea](https://github.com/github/choosealicense.com/pull/669#issuecomment-557837719) to use licensee master in tests. Merging after >2.5 years. 😄

**Pull request merged**
