### PR TITLE
Add normalize.css v2.1.3 minified with clean-css.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by haacked** [comment]
Could you provide some background for this proposed change?

**Comment by XhmikosR** [comment]
The reason I made this change is because normalize.css is a lot more feature complete than what you had there which I assume was some kind of reset stuff.

BTW, I was thinking maybe it would be simpler to add a `ul { list-style-type: none; }` instead of adding `list-style-type: none;` to most individual `ul`. What do you think of this?

EDIT: I went with this approach since it results in less code.

**Comment by haacked** [comment]
I like less code. I want to make sure our designer sees this before I merge it. /cc @jasonlong

**Comment by jasonlong** [comment]
I'm surprised I didn't use normalize in the first place. This works for me. :thumbsup:

**Comment by haacked** [comment]
Great! @XhmikosR can you merge upstream master into your branch (or rebase it against upstream master if you're so inclined).

**Comment by XhmikosR** [comment]
Done.

**Pull request merged**
