### PR TITLE
Remove confusing and inaccurate [no-]sublicensing property

### PR DESCRIPTION
**Pull request by mlinksva**
LGPLv3 doesn't allow sublicensing, justg as LGPLv2 doesn't as
former is additional permissions for GPLv3 and these don't include
sublicensing

### CODE REVIEW

**Comment by bkeepers** [comment]
This was removed in #303 due to discussion in #10. My understanding is that sublicensing is technically forbidden, but the copyleft makes the ability to sublicense irrelevant.

/cc @mebmink

**Comment by mlinksva** [comment]
Well #303 was an incomplete implementation as there's inconsistency across copyleft licenses represented at choosealicense.com presently.

#10 is muddled as discussion of sublicensing usually is. It's definitely not about conveying the work. It's the ability of a licensee to license the rights it has gained through the license to its licensees. That's not needed for open source licenses as you're always getting a direct license from each contributor.

I wouldn't mind much just removing sublicensing / no-sublicensing properties altogether from the site as it is a confusing concept and not one people choosing a license need to understand.

But if we're going to keep the property it's pretty silly to present it inaccurately.

**Comment by mlinksva** [comment]
(Thanks for the pointer to past discussion BTW; I should've searched first.)

**Comment by mlinksva** [comment]
Noticed additional inaccuracies. Convinced myself best to remove description of sublicensing from the site. Even if made accurate would be confusing and not helpful in choosing a license. Noise at best, more realistically anti-information.

**Comment by benbalter** [comment]
@mlinksva defer to your judgement here.

**Pull request merged**
