### PR TITLE
Appendix/table of all repo licenses; closes #388

### LINKED ISSUE #388: List all licenses in _licenses at bottom of /licenses (or /about?) for discoverability
I believe this has been suggested multiple times but the latest is https://github.com/github/choosealicense.com/pull/386#issuecomment-207289224

This would simply be a list of links rather than an inline description of each license as done for select licenses on /licenses

### PR DESCRIPTION
**Pull request by mlinksva**
This is quite ugly. Improvements or something better welcomed.

Closes #388 see there for motivation.

Additionally I wish I had made a table like this a long time ago, would have caught more license description errors earlier.

### CODE REVIEW

**Comment by mlinksva** [comment]
Screenshot. Hmm, "patent use" permissions and limitations columns could be merged.

choosealicense-appendix

**Comment by benbalter** [comment]
Wow. I like that **a lot**. :smile:

**Comment by waldyrious** [comment]
This is wonderful. Eventually we should be able to apply filters to the table and sort the rows, but for a start it's great! I might submit styling tweaks later on when I get the time, but I like how it looks already :)

**Comment by mlinksva** [comment]
I'm going to go ahead and merge this. Definitely welcome pull requests to make it look better or to allow sorting, etc.

Note that I've not made the license property tooltips you can see eg in /licenses or on individual license pages work (hover over eg "commercial use" on one of those pages). The CSS and Javascript (relevant files are `assets/css/application.scss` and `assets/js/app.coffee`) for those tooltips currently require a specific structure with bullets, but probably could be made more flexible. An alternative that might even be more useful would be a legend.

**Comment by ionas** [comment]
Great work! @ https://github.com/github/choosealicense.com/pull/406#issuecomment-217962912

So where is http://choosealicense.com/appendix/ now linked from ... I could not find it on the home page - so either I am blind or its no there or the discover-ability towards that page/link maybe isn't good.

**Comment by ionas** [comment]
The headers could/should link to the feature pages (e.g. "patent use", "hold liable") etc.

**Comment by mlinksva** [comment]
@ionas thanks. It's linked from /about. User can navigate from http://choosealicense.com/ to http://choosealicense.com/licenses/ to (linked at bottom) http://choosealicense.com/about/ to http://choosealicense.com/appendix/ if they really are digging information about licenses. I know you'd prefer all on one page but that's how it works for now.

Re the headers linking to feature pages, those don't exist. A legend would probably be easiest now, but an eventual glossary (#238) could be another link target. I think much less of a problem since tooltips work in every cell now (#408).

**Comment by htstudios** [comment]
I'd love a link at the bottom of the main page for now: 'Compare licenses' - thanks for your incredible work, and don't feel discouraged by my criticism!

**Comment by mlinksva** [comment]
@jhli that sounds like a request rather than criticism! I'm pretty disinclined to link from `/` to `/appendix` at this point. I enjoy seeing everything in a giant table and maybe @benbalter's twitter followers [do too](https://twitter.com/benbalter/status/730088812441829376) (I assume retweets and faves and absence of negative replies indicate positive sentiment, but I'd defer to someone who studies such things) but a big table can only help mitigate cognitive overhead of lots of redundant choices so much...`/licenses` is the next destination for someone learning about licenses if `/` doesn't satisfy.

One of the great things about the web (well, the web of pages, sometimes lost with poorly designed single page apps!) is that if you think some page other than the home page is most useful to people you're communicating with, you can send them a link to that most useful page. As you thankfully don't need permission, I instead encourage you to send/link to http://choosealicense.com/appendix often. 😄

**Comment by PatMyron** [comment]
A table row for https://choosealicense.com/no-permission/ would help compare everything on one page

**Pull request merged**
