### PR TITLE
consolidate no license info in /no-license, remove from /licenses

### PR DESCRIPTION
**Pull request by mlinksva**
As noted in #196 (which this fixes) the provided metadata for "no license" isn't accurate. My preferred fix is to remove it. The option is available from the home page, there's no need to represent again on /licenses (no license isn't one).

I don't think this should break anything (e.g., "None" seems to be a hardcoded default in the GitHub new repo drop-down rather than being pulled from the choosealicense dataset) and documentation for the in-preview https://developer.github.com/v3/licenses/ doesn't show "no license" in response to list request. It's quite likely that I'm missing something.

### CODE REVIEW

**Comment by benbalter** [comment]
The original thinking was the `/no-license` was intended for code publishers, to better understand what rights they grant (or retain), but _not_ licensing their code. The `licenses/no-license` was intended to be able to provide code consumers information on what rights they receive / don't receive, thinking of them less as licenses, and more like "license states". I'm not totally against it, per se, but if we remove the `licenses/no-licenses`, code consumers lose value, in that they no longer have the side bar rights metadata.

In terms of github, no-license is considered a "hidden" license, meaning it doesn't appear in the drop down or on `api.github.com/licenses`, but if a repository has no license (I think) we return the no-license metadata (but I may be wrong). Easy enough to fix upstream or modify the behavior depending on the above discussion.

**Comment by mlinksva** [comment]
Thanks for the background thinking.

The side bar rights metadata isn't accurate so I don't think consumers are benefiting. But, good point on providing useful info to consumers. I added a practical section to /no-license for users. What do you think?

**Comment by benbalter** [comment]
What metadata would you put in the sidebar, to make it accurate? We'll likely want to reimplement the "no-license" license within Licensee (or maybe leave it here, but make it hidden).

**Comment by mlinksva** [comment]
`curl -H "Accept: application/vnd.github.drax-preview+json" https://api.github.com/repos/github/testrepo` obtains `"license": null`. That's the right behavior I think, rather than returning no license metadata. If we haven't detected a license, we just don't know. Returning the no license metadata would make it seem like we did.

The most accurate metadata for no license of the type we're providing for licenses is no metadata. For licenses, the metadata describes what the license permits, and the requirements and prohibitions that condition and scope those permissions. For no license, we have a different situation, where the metadata is trying to describe default copyright law. This is a lot messier. We can accurately say that the copyright holder hasn't given any express permissions, but the existing metadata scheme doesn't have a way of expressing that. What the user is free to do due to an implied license or copyright limitations and exceptions is unclear at best. Requirements just aren't relevant. Some of the prohibitions could be stated with relatively more certainty, but it's hard to not over-describe what is forbidden by default, make it seem what is not listed as forbidden might be allowed (ambiguous at best, as noted previously), or both. If there's a really strong use case for providing this type of metadata for default copyright status, I guess we could provide only forbiddens, but I'd rather just not try to describe default copyright, again, unless there is a really strong reason to do so.

**Comment by benbalter** [comment]
All right.  You're logic makes sense (sorry it took me a while to get there). Once this merges, I'll deal with the impact to Licensee, to ensure we can keep pulling updates into GitHub.

**Edit**: Thanks for taking the time to walk me through your thinking.

**Comment by mlinksva** [comment]
Thanks as always for taking the time to lay out the context and making me articulate my thinking. I'll go ahead and merge now.

**Pull request merged**
