### PR TITLE
Add description for the Affero GPL license

### PR DESCRIPTION
**Pull request by waweber**
This will add a description to the Affero GPL entry in the licenses page.

Signed-off-by: Wes Weber wweber@wesweber.com

### CODE REVIEW

**Comment by afeld** [comment]
Is that the defining feature of the AGPL?  Seems like it could be reworded to

> The Affero GPL is based on the GPLv3, but includes clauses...

to give the "base" for the deviation, if my interpretation of the [Wikipedia article](http://en.wikipedia.org/wiki/Affero_General_Public_License) is correct.

**Comment by haacked** [comment]
@afeld: perhaps submit a counter-proposal PR? :smile:

**Comment by afeld** [comment]
@Haacked I dunno if I want to be responsible for getting it wrong :-)

**Comment by haacked** [comment]
@afeld LOL! Hey @hoolio, @benbalter, or the legion of new legal eagles. Would one of you like to take a crack?

**Comment by mayashino** [comment]
Deferring to @talniv on this one.

**Comment by haacked** [comment]
Closing this in favor of #111. Please take a look at that one and provide comments. :smile: Thanks!

**Pull request closed without merging**
