### PR TITLE
Remove background

### PR DESCRIPTION
**Pull request by bkeepers**
The textured background makes the site feel a little dated to me. I'm not familiar with the history of the design, but was curious what everyone would think about dropping the background. Thoughts?

choosing_an_oss_license_doesn t_need_to_be_scary_-_choosealicense_com

licenses_-_choosealicense_com

apache_license_2_0_-_choosealicense_com

/cc @github/choosealicense-com

### CODE REVIEW

**Comment by benbalter** [comment]
I want to say it might have been @cobyism's doing?

**Comment by jasonlong** [comment]
Yep, that was my doing and I definitely agree @bkeepers. :thumbsup: from me.

**Comment by bkeepers** [comment]
:cool:, thanks @jasonlong.  Anyone else have thoughts?

**Comment by benbalter** [comment]
:shipit:

**Pull request merged**
