### PR TITLE
Fix instructions for Artistic 2.0 (follow-up #333)

### PR DESCRIPTION
**Pull request by waldyrious**
cf. #103, #310 and #333
cc @mlinksva, @benbalter, @bkeepers and @Haacked

### CODE REVIEW

**Comment by mlinksva** [comment]
Thanks, good catch.

**Comment by waldyrious** [comment]
Sorry, there's a small mistake in the text: where it says "they refer to", it should say "it refers to". Can you make that fix directly? I don't think a new PR is warranted.

**Comment by mlinksva** [comment]
> Do not replace the copyright notice (year, author) — it refers to the license itself, not the licensed project.

It.itself reads a bit awkwardly. How about:

> Do not replace the copyright notice (year, author), which refers to the license itself, not the licensed project.

**Comment by waldyrious** [comment]
Sounds good :)

**Pull request merged**
