### PR TITLE
Added the WTFPL licence

### PR DESCRIPTION
**Pull request by pingiun**
I think the WTFPL is a good addition to the licenses because it's the most open license out there. It's a good option if you want to go full open source.

### CODE REVIEW

**Comment by benbalter** [comment]
@Jell-E thanks for the pull request. Believe this is a dupe of https://github.com/github/choosealicense.com/pull/15 and https://github.com/github/choosealicense.com/pull/17.

I'm :-1: for the reasons previously mentioned, but glad to revisit the discussion if there's an academic argument for its inclusion. 

Please note, the [goal of the project](https://github.com/github/choosealicense.com#immediate-goals) is not to be comprehensive, but to demystify licensing choices for the average user.

**Comment by benbalter** [comment]
@Jell-E I'd be happy to merge this pull request given two changes:
1. Per #273, please add `hidden: true` to the YAML front matter
2. In the event that it's listed elsewhere, please change the title to `F***` and remove `the fuck` from the description (the license body is fine)

**Comment by pingiun** [comment]
@benbalter Would it be suitable for merging now?

**Comment by benbalter** [comment]
Awesome. Thanks @Jell-E! :hamster:

**Pull request merged**
