### PR TITLE
Add BSD-4-Clause license

### PR DESCRIPTION
**Pull request by okeuday**
* Fixes https://github.com/benbalter/licensee/issues/195

The requirements are met:
1. BSD-4-Clause
1. https://www.gnu.org/licenses/license-list.en.html#GPLIncompatibleLicenses lists it (2nd free category)
1. https://github.com/search?q=BSD+filename%3ALICENSE&type=Code (difficult to distinguish between the different BSD types, the BSD-4-Clause is commonly used to ensure credit is received for open-source work that may be used commercially)

### CODE REVIEW

**Comment by okeuday** [comment]
The CI build fails due to wanting to use ruby 2.4.0 instead of 2.3.3, though it has test failures if it is changed to 2.4.0.  So, this failure should be expected in the master branch and is not related to these changes.

**Comment by mlinksva** [comment]
Thanks @okeuday ! I fixed the failures.

https://github.com/search?utf8=%E2%9C%93&q=%22All+advertising+materials+mentioning+features+or+use+of+this+software+must+display+the+following+acknowledgement%22+filename%3ALICENSE&type=Code is more specific but still qualifies.

2 things:

- There are some differences between this text and https://spdx.org/licenses/BSD-4-Clause.html (numbered bullets, words in disclaimer). I'd prefer to go with SPDX version unless there's evidence they have it wrong because an eventual goal is to source texts from them.
- Related to figuring out whether the SPDX version is correct, 3 `using` examples would be helpful (does use in the wild match?); this will be required soon, see https://github.com/github/choosealicense.com/issues/508 I just haven't gotten around to writing the tests.

Could you update the PR with examples and license text matching the SPDX text or a reason that is wrong?

**Comment by okeuday** [comment]
@mlinksva The BSD-4-Clause was used in NetBSD until 2008 (OpenBSD and FreeBSD changed their license around that time too), but despite that change, the older BSD licensed source code has found itself info other projects like ReactOS (https://www.reactos.org/) and uClinux (http://www.uclinux.org/).  These projects don't appear to use github for their repositories, though their source code has found its way into the github search due to other people creating repositories with the source code stuck at a certain point in the past.  I have used it in CloudI (http://cloudi.org) which does have a github repo at https://github.com/CloudI/CloudI/ but I plan on changing it, after having read more about it.  This is difficult to check, since you may unintentionally limit yourself to github or usage of git.

I updated the license to match the SPDX version.  I am not sure about the best github search to find "nontrivial and regular/detectable uses" (to satisfy https://github.com/github/choosealicense.com/issues/508) but I would like to think the information above is enough.

To some degree I would hope that GitHub isn't attempting to provide legal advice with its decisions, since attempting to provide legal advice without being a lawyer should be a problem (in the US at least).  To avoid that problem, it seems simplest to support any license and just rely on popularity to show what is best (natural selection).

**Comment by mlinksva** [comment]
GitHub isn't attempting to provide legal advice, see the site disclaimer. 'Natural selection' is fine, but there are a lot of licenses, and for older ones especially, even defining what counts as an instance of a particular license is [fuzzy](https://github.com/benbalter/licensee/issues/98#issuecomment-220885877). So we defer as much as possible to external authorities and evidence of a license's use 'in the wild'. Note `using` examples do not need to be on GitHub or use git; their `LICENSE` file just needs to have a URL.

**Comment by okeuday** [comment]
@mlinksva I am no longer interested in pursuing this.  Feel free to close the issue or to pursue it separately.

**Comment by mlinksva** [comment]
@okeuday appreciated.

If anyone else reading now or later wishes to follow up on this, please do.

**Comment by waldyrious** [comment]
I tried to find projects on GitHub licensed under BSD-4-Clause via Google BigQuery's GitHub tables, using the same method described [here](https://github.com/github/choosealicense.com/pull/438#issuecomment-230150424), but the query returned no results :/

``` sql
SELECT gh_licenses.repo_name, gh_since2015.num_stars
FROM [bigquery-public-data:github_repos.licenses] AS gh_licenses
JOIN (
    SELECT repo.name, COUNT(*) AS num_stars
    FROM TABLE_DATE_RANGE([githubarchive:day.], TIMESTAMP('2015-01-01'), CURRENT_TIMESTAMP())
    WHERE type = "WatchEvent"
    GROUP BY repo.name
) AS gh_since2015
ON (gh_licenses.repo_name == gh_since2015.repo.name)
WHERE license="bsd-4-clause"
ORDER BY num_stars DESC
```

Perhaps GitHub's new GraphQL API could eventually help here, but I couldn't figure out a way to search for repos by license (in any case, I suppose it would only work after BSD-4-Clause is added to choosealicense.com anyway)

**Comment by waldyrious** [comment]
FYI, the BigQuery method does work for other licenses -- here are the ten most starred repos with the bsd-3-clause license:

- [FreeCodeCamp/FreeCodeCamp](https://github.com/FreeCodeCamp/FreeCodeCamp)
- [facebook/react](https://github.com/facebook/react)
- [facebook/react-native](https://github.com/facebook/react-native)
- [facebookincubator/create-react-app](https://github.com/facebookincubator/create-react-app)
- [golang/go](https://github.com/golang/go)
- [d3/d3](https://github.com/d3/d3)
- [django/django](https://github.com/django/django)
- [ecomfe/echarts](https://github.com/ecomfe/echarts)
- [facebook/immutable-js](https://github.com/facebook/immutable-js)
- [scikit-learn/scikit-learn](https://github.com/scikit-learn/scikit-learn)

**Comment by mlinksva** [comment]
@waldyrious nice. If you feel like it, please make a PR to add example uses to BSD-3-Clause. Lots of good choices there, but offhandedly react, go, and django nicely demonstrate the apparent prestige of the license.

**Comment by mlinksva** [comment]
Closing this as nobody has expressed interest in following up, including me. :smile:

**Pull request closed without merging**
