### PR TITLE
Update modernizr.js to v2.7.1.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by haacked** [comment]
Thanks! Any specific improvements to call out in this release of modernizr or mostly bug fixes?

**Comment by XhmikosR** [comment]
This update should really affect choosealicense but you know, it doesn't hurt either :)

**Comment by haacked** [comment]
> IOperatingSystemFacade

Did you mean "shouldn't"? Yeah, I like to stay up to date. Especially if someone else does the work to upgrade and test. Thanks!

**Comment by XhmikosR** [comment]
Oops yeah I meant shouldn't :P

**Pull request merged**
