### PR TITLE
Add Boost Software License 1.0.

### LINKED ISSUE #223: add boost software license support
It is basically a BSD/MIT license with no required attribution in binary distributions.
License can be found in http://www.boost.org/LICENSE_1_0.txt

Comparison details here: 
http://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

Quoting boost website:
"This license, which is very similar to the BSD license and the MIT license, should satisfy the Open Source Initiative's Open Source Definition: (i) the license permits free redistribution, (ii) the distributed code includes source code, (iii) the license permits the creation of derivative works, (iv) the license does not discriminate against persons or groups, (v) the license does not discriminate against fields of endeavor, (vi) the rights apply to all to whom the program is redistributed, (vii) the license is not specific to a product, and (viii) the license is technologically neutral (i.e., it does not [require] an explicit gesture of assent in order to establish a contract between licensor and licensee).

This license grants all rights under the owner's copyrights (as well as an implied patent license), disclaims all liability for use of the code (including intellectual property infringement liability), and requires that all subsequent copies of the code [except machine-executable object code], including partial copies and derivative works, include the license."

### PR DESCRIPTION
**Pull request by joto**
Fixes #223

### CODE REVIEW

**Comment by mlinksva** [comment]
@joto thanks!

I made a few changes:
- same-license is not a limitation and doesn't apply in any way to BSL-1.0
- other licenses with a per-file notice recommendation get that added to the note field
- have the description mention the reason for this license existing, binary distribution without notices (IIUC)
- remove using: pending an example that can be followed by others and detected eg on GitHub, see https://github.com/github/choosealicense.com/blob/gh-pages/README.md#optional-fields and see #358 #372 #377

If you see anything wrong please let me know or make more commits to this branch. Feel free to suggest 'using' examples now, or another time (it's an optional field).

Finally, could you sign the CLA -- see "details" link next to failing test?

**Comment by joto** [comment]
@mlinksva Looks great. Thank you!

**Comment by janwilmans** [comment]
I still cant choose the boost license if I create a new LICENSE.md. boost is not available as a template?

**Comment by mlinksva** [comment]
Update -- though there's no UI to choose Boost from, you can load the license up in the chooser with the following (replace `<user>` and `<repo>` with yours):

```
https://github.com/<user>/<repo>/community/license/new?branch=master&template=bsl-1.0
```

**Comment by janwilmans** [comment]
Thanks, that worked for me...

**Pull request merged**
