### PR TITLE
Remove untenable assertion from goals

### PR DESCRIPTION
**Pull request by ghost**
Whether in civil rights, human rights, land rights, "intellectual property" rights (as in this case) or any other rights, the act of deciding who ought to be granted which rights in which circumstances is not only inherently political, it is the very essence of politics. Therefore, it is preposterous for choosealicense.com, if it is to be meaningful, to aim to be "Politics Free".

### CODE REVIEW

**Comment by tekkub** [comment]
"Politics" may have been a poor choice of word, but I think that the spirit of that bullet point should be preserved.  I have always interpreted that spirit to be "we don't want to start a :fire: :facepunch: over what license is the best, or the internal conflicts (i.e. politics) of any group of people involved with any of these licenses."

In short, this isn't the place for people to get on a soapbox about any license.

**Comment by ghost** [comment]
Better? :)

**Comment by haacked** [comment]
I like it! @benbalter?

**Comment by afeld** [comment]
:+1:

**Comment by benbalter** [comment]
How is does "Our goal is to help you find a license that meets _your_ goals." interplay with "Not comprehensive.", which is a lower priority. If the license that meets my needs isn't listed, this would suggest that we should now add it.

The original pull request took issue with the word political. The distinction's semantic, but if that's the issue at hand, let's just swap `non-partisan` for `not political`. Why is the 2nd half of the line insufficient as is?

**Comment by tekkub** [comment]
I think this version communicates our intentions much better, I like it.

> If the license that meets my needs isn't listed, this would suggest that we should now add it.

We link to some external sites with more comprehensive lists on our about page.  I think "I don't have a license that covers your needs, but here are some other resources that might" qualifies as "helping".

**Comment by benbalter** [comment]
I'm not as strongly opinionated on this one, so @tekkub and @Haacked I'll defer to your judgement.

**Comment by haacked** [comment]
selfie-0

**Comment by ghost** [comment]
Thanks! :+1: all round :)

**Pull request merged**
