### PR TITLE
Markdownify

### PR DESCRIPTION
**Pull request by XhmikosR**
Minor tweaks for better HTML output.

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW I'm not sure if we want to be consistent with the angle brackets. I mean, only one license is using them (agpl), while 4 others use square brackets.

Let me know what you prefer and I can take care of this.

**Comment by haacked** [comment]
All the GPL licenses have angle brackets in them. what's the result of this change to those licenses?

**Comment by XhmikosR** [comment]
They are shown as they are, properly after they are converted to use the html entities.

**Comment by XhmikosR** [comment]
For example for GPLv3

``` html
You should have received a copy of the GNU General Public License
along with this program.  If not, see &lt;http://www.gnu.org/licenses/&gt;.
```

**Comment by XhmikosR** [comment]
Only downside, if we can call it that, is that due to Jekyll's issue with whitespace, when one copies the license text to clipboard they end up with useless trailing spaces.

**Comment by haacked** [comment]
Ewww. People hate that. There's no hack for that?

**Comment by XhmikosR** [comment]
I'll check again but it's time this is fixed in Jekyll...

**Comment by XhmikosR** [comment]
With `strip_newlines` it beats the point since we end up with a one line text. `newline_to_br` results in useless empty lines. `replace` doesn't accept regex as far as I can tell.

Perhaps it's time we add a plugin to minify the HTML?

**Comment by XhmikosR** [comment]
Potential candidates:

https://gist.github.com/mytharcher/2758691
https://github.com/imathis/jekyll-minify-html

**Comment by XhmikosR** [comment]
@Haacked: Please check #184 for a quick workaround.

**Pull request merged**
