### PR TITLE
Add more info on MPL 2.0

### PR DESCRIPTION
**Pull request by Zimmi48**
This pull request is composed of two separate commits adding the following:
- a note on the recommended boilerplate (as for GPL and Apache)
- three examples of software under this license (as for GPL, Apache and MIT)

### CODE REVIEW

**Comment by mlinksva** [comment]
Thanks! Could you make the examples link to LICENSE (or similar) files in the relevant source repositories? See the `using:` examples for other licenses.

**Comment by Zimmi48** [comment]
Done for LibreOffice!

As for Firefox and Thunderbird, there are difficulties:
- First, they don't have a separate repository. Instead, lots of project of the Mozilla foundation are in one single repository.
- At the root of this repository, we find this https://dxr.mozilla.org/mozilla-central/source/LICENSE but it isn't very informative. It refers to an HTML file: https://dxr.mozilla.org/mozilla-central/source/toolkit/content/license.html but that's not very readable, and to the page on Mozilla's website I have linked to.
  With a bit more searching, I was able to find this: https://dxr.mozilla.org/comm-central/source/suite/installer/license.txt. This is a very readable license file for the installer of the Seamonkey suite (which packages in particular Firefox and Thunderbird).
  Do you think I should replace the link with this one?

**Comment by mlinksva** [comment]
For other licenses we've just used lesser known examples that are more straightforward, such that they an serve as implementation examples for someone new to open source licenses. See discussion around ISC at https://github.com/github/choosealicense.com/issues/377

**Comment by waldyrious** [comment]
Again, that compromise pains me. I wish popular projects had more straightforward license communication practices...

**Comment by Zimmi48** [comment]
I understand this viewpoint. If I can be the devil advocate, these popular projects are much older than Github and transitioning to a smoother development process such as the one promoted by Github or one of its competitors can be difficult.

Anyway, I have looked to some alternative software to highlight and so far, I have found the following:
- Firefox for iOS: https://github.com/mozilla/firefox-ios/blob/master/LICENSE (the problem is that people won't necessarily understand why citing Firefox for iOS and not just Firefox).
- This page http://spiceprogram.org/licenses/#MPL2 mentions TimelineJS. I don't know the project but it has thousands of stars at https://github.com/NUKnightLab/TimelineJS. However, this appears not to be the right repository to refer to so instead the link could be to https://github.com/NUKnightLab/TimelineJS3/blob/master/LICENSE.

PS: If you guys at Github allowed a real search filter for repositories by license, it would be much simpler to find relevant examples...

**Comment by waldyrious** [comment]
> PS: If you guys at Github allowed a real search filter for repositories by license, it would be much simpler to find relevant examples...

+💯

**Comment by mlinksva** [comment]
Definitely not judging older or popular projects with more complicated licensing or their main license notice somewhere other than an easily identifiable repository. They're fine! They just don't serve as great examples for someone just choosing a license to follow. Has nothing to do with whether they've migrated to GitHub. Plenty of projects with complicated licensing are on GitHub, and many of the examples for other licenses point to implementations not hosted on GitHub.

Firefox for iOS and TimelineJS3 seem like acceptable examples to me, but https://github.com/servo/servo/blob/master/LICENSE could be a good replacement for Firefox for iOS.

I know, a real search filter on license would be great.

**Comment by Zimmi48** [comment]
Cool, thanks for the pointer.
Pull request updated ;)

**Pull request merged**
