### PR TITLE
isc.txt: wrap text of the license to 80 columns

### PR DESCRIPTION
**Pull request by waldyrious**
As a bonus, the line breaks are closer to the clause boundaries,
which hopefully makes the text slightly easier to read.

### CODE REVIEW

**Comment by mlinksva** [comment]
There are no tests to enforce, but the standard [here](https://github.com/github/choosealicense.com/blob/d6c6f9c4af631a30375313249846ef6402426e99/CONTRIBUTING.md#adding-a-license) is 78 see #74 for explanation. Feel free to argue that is the wrong decision.

Does 78 obtain the same result for ISC?

Related, maybe worth additional issues but just noting here for now:

1. It'd be nice to have a test enforcing wrapping at 78, ideally comparison with output of (2), but even a stupid test that no line in license text is >78 characters would be a start.
2. Is it possible to automatically wrap all licenses at 78 and have output make sense? Or is manual intervention required? I suspect a fair amount of special casing would be needed, but haven't tried. In addition to being used for tests, could be part of script to ingest license texts from SPDX in #489.

**Comment by mlinksva** [comment]
(re 2 above, it would be easier to get good output if wrapping as part of structured SPDX XML license to text, maybe in <https://github.com/spdx/tools/blob/master/src/org/spdx/licensexml/LicenseXmlHelper.java>, rather than attempting to wrap plain text.)

**Comment by waldyrious** [comment]
> Feel free to argue that is the wrong decision.

Honestly, the resolution in that thread sounds more as an arbitrary choice than a pondered decision. That said, @bendiken's comment in that thread (and particularly the SO link within it) does provide some good points in favor of a max width of less than 80 chars, so I won't contest the resolution.

> Does 78 obtain the same result for ISC?

No. Several lines in this PR are 79 or 80 characters long.

> It'd be nice to have a test enforcing wrapping at 78

I agree that such tooling would be helpful, but I'm not able to contribute to that.

> Is it possible to automatically wrap all licenses at 78 and have output make sense?

I'm not sure what you mean by "make sense". Do you have any specific example in mind?

As for this PR, feel free to close it in light of the current guideline of 78 chars.

**Comment by mlinksva** [comment]
First draft of test in #552.

By "make sense" I mean lines that shouldn't be wrapped, aren't, and wrapping maintains indentation appropriately. That requires some smarts about when lines that aren't separated by a newline shouldn't be potentially merged, and figuring out what the appropriate indentation is for each line. Licenses with lists or indented items (eg AFL-3.0, Apache-2.0) cause problems for the `fmt` command, so something smarter than that is required.

Closing this, thanks for the idea!

**Pull request closed without merging**
