### PR TITLE
Use jekyll-sitemap plugin

### PR DESCRIPTION
**Pull request by pathawks**
No need to reinvent the wheel, we can use the [jekyll-sitemap](https://github.com/jekyll/jekyll-sitemap) plugin.

This is [fully supported by GitHub pages](https://help.github.com/articles/sitemaps-for-github-pages).

### CODE REVIEW

**Comment by haacked** [comment]
/cc @benbalter 

What's with the Travis build?

**Comment by benbalter** [comment]
Will likely need to `bundle update` to get jekyll-sitemap into the `Gemfile.lock`

**Comment by pathawks** [comment]
Yay! Fixed the tests with `bundle update`!

Thanks for pointing that out.

**Comment by benbalter** [comment]
Awesome! Thanks again @pathawks. :tada:

**Pull request merged**
