### PR TITLE
making GPL text easier to understand

### PR DESCRIPTION
**Pull request by josinalvo**
I found the GPL text a bit dry. Does one need to know what copyleft is to choose it ?

Tryed to right a neutral text (not pro, not against) that makes it clearer

### CODE REVIEW

**Comment by benbalter** [comment]
See https://github.com/github/choosealicense.com/issues/51 and https://github.com/github/choosealicense.com/pull/177 for some additional context. It seems to many people, the GPL means many things, and it'd be great to harmonize the parallel efforts.

**Comment by josinalvo** [comment]
I want people to "pay it forward"

The GPL (<a href="licenses/gpl-2.0/">V2</a> or <a href="licenses/gpl-3.0/">V3</a>) is a copyleft license: You allow A to see and alter the code, but if A gives (or sells) it to B, A must allow B to see and alter as well. V3 is similar to V2, but if A puts the code in a machine, then gives that machine to B, the machine must allow B to run altered versions of the code.

**Comment by josinalvo** [comment]
How about that ?

I changed the title to help with #51 concerns
(and, for some reason, changed the whole damn text ...)

**Comment by bkeepers** [comment]
Thanks for the suggestion. Since this discussion hasn't been active for a while, I'm going to close this for now. We're happy to continue the conversation though.

**Pull request closed without merging**
