### PR TITLE
WIP: Vendor license text from SPDX API

### PR DESCRIPTION
**Pull request by benbalter**
[Whitespace insensitive diff](https://github.com/github/choosealicense.com/pull/489/files?w=1)

### CODE REVIEW

**Comment by mlinksva** [comment]
Love it. Things noticed at a glance:

- Something would need to be done with the Optional sections in CC0/-BY/-SA.
- ISC copyright holder isn't templated, which is probably a bug on SPDX side.
- Variable fields in the BSD licenses.

**Comment by bkeepers** [comment]
I think the license data comes from https://github.com/spdx/license-list

**Review by ditta95aR — APPROVED** [review]

**Comment by mlinksva** [comment]
A _long_ way from merging, but I might use it when I'm bored or stuck as a tool to try to iron out differences between the collection here and texts in SPDX. One for today: https://github.com/spdx/license-list-XML/pull/482

**Comment by mlinksva** [comment]
More PRs and issues, mostly to reduce difference between the license texts here, their origin, and the SPDX catalog, or accommodate those differences (eventually could build a new licensee matcher that leverages the SPDX XML files and license matching rules) https://github.com/search?q=org%3Aspdx+author%3Amlinksva&type=Issues&utf8=%E2%9C%93

**Comment by mlinksva** [comment]
Version 3.0 of the SPDX license list has been released, and from a word-diff perspective, it's closer to what we have here, but its output formats contain no blank lines, which wouldn't work for this project. I've opened https://github.com/spdx/license-list-data/issues/16 and will see if that might be addressed before bringing the 3.0 SPDX changes into this branch.

**Comment by mlinksva** [comment]
There are some new(?) issues with the [text renderings](https://github.com/spdx/license-list-data/tree/699daa5f549c07c645986b7680bc8fce7320c6ec/text) from https://github.com/spdx/license-list-data revealed by trying to vendor them, most obviously of URLs with optional `s` in protocol. I'll file issues or PRs there (or https://github.com/spdx/LicenseListPublisher as appropriate) when I get a chance to look again, but anyone else feel free to go ahead. 😄

**Comment by mlinksva** [comment]
Also older text renderings in license-list-data had long lines. Now they're wrapped. Re-wrapping to 78 chars here (without a lot of added intelligence) causes all kinds of problems.

**Review by Edredd7 — COMMENTED** [review]
Duplicate of #

**Pull request closed without merging**
