### PR TITLE
Compress images.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by haacked** [comment]
We had a recent commit where we compressed images. What were the savings here?

/cc @jasonlong

**Comment by XhmikosR** [comment]
Not much, but it's free anyway ;)

```
before: 15,1 KB (15.463 bytes)
after:  14,8 KB (15.164 bytes)
```

**Comment by haacked** [comment]
Well my non-designer eye can't tell the difference. :smile: Thanks!

**Comment by haacked** [comment]
thumbsup-mattleblanc

**Comment by jasonlong** [comment]
:thumbsup:

**Pull request merged**
