### PR TITLE
remove BOM from eupl-1.1.txt which caused it to not render

### PR DESCRIPTION
**Pull request by mlinksva**
BOM = byte order mark

### CODE REVIEW

**Comment by benbalter** [comment]
:+1: I'm not sure why tests are failing. Merging in master _might_ resolve it.

**Comment by mlinksva** [comment]
Actually, I can reproduce failure locally, which demonstrates I didn't run `rake test` before pushing.

Here's what I think's happening:
- _site/licenses/eupl-1.1/index.html contains a href to http://choosealicense.com/licenses/eupl-1.1/
- html-proofer checks all links in _site
- http://choosealicense.com/licenses/eupl-1.1/ (or any newly introduced link, not yet live) of course obtains 404

Braindead fix would be to have test tell html-proofer to ignore choosealicense.com links, with obvious downside of not catching unintentionally broken links within the site.

Sophisticated fix I guess would be to compare links in origin/gh-pages and local branch, and tell html-proofer to ignore choosealicense.ccom links introduced locally.

Or even better, looking at https://github.com/gjtorikian/html-proofer `href_swap` on choosealicense.com links to have those links tested locally rather than against live site. I'll see if I can make that work.

But if my speculation about how things work is obviously off-base, please advise. :smile:

**Comment by mlinksva** [comment]
That seems to do it, and if I introduce a http://choosealicense.com/... link that doesn't exist locally, the test fails, as it should.

**Comment by benbalter** [comment]
~~Tests pass for me locally without the change in 96fc8b1. Theoretically, there shouldn't be any choosealicense.com links locally, since everything uses site.url or site.github.url. Do you know where the link is in the page?~~

**Comment by benbalter** [comment]
Just kidding. I was using your fix. I think I see what's going on.

**Comment by mlinksva** [comment]
`<link rel="canonical" href="http://choosealicense.com/licenses/eupl-1.1/" itemprop="url" />`

**Comment by benbalter** [comment]
Yep. It's via the SEO tag plugin. Looks like your fix is the simplest. :+1:

**Pull request merged**
