### PR TITLE
Include list of tools

### PR DESCRIPTION
**Pull request by afeld**
@talniv and I discussed this IRL today, but figured it would be helpful to include links to some tools around licensing and dependencies.  I'm sure there are others I don't know about that would be helpful to include, too.

/cc @BrentWheeldon @dblock @tchemit

### CODE REVIEW

**Comment by afeld** [comment]
screen shot 2013-10-23 at 12 55 58 am

**Comment by afeld** [comment]
/cc @amutz @nowells

Hopefully all these people I'm CCing who have touched these various projects don't mind me spamming them :grin:

**Comment by haacked** [comment]
Looks good! :shipit:

**Comment by gjtorikian** [comment]
Where's http://www.addalicense.com/ at ?! :frowning:

**Comment by afeld** [comment]
@gjtorikian PR that bad boy

**Pull request merged**
