### PR TITLE
Limit the line length in the 'license' files to 78 characters.

### LINKED ISSUE #74: Set Line Width to 78 Characters
It is pretty common for text editors, and IDE's to default line wrapping to 78 characters.  It can be annoying to have to modify every license because it breaks to 'early', messing with the format.  

It would be appreciated to require that the content of all licenses not exceed 78 characters.  I'll be more than happy to submit a pull request if this is something that will be accepted.

### PR DESCRIPTION
**Pull request by derks**
This pull request limits the line length in the 'license' files to 78 characters.

Fixed #74.

### CODE REVIEW

**Comment by XhmikosR** [comment]
This can't work as you can see from the Travis failure...

**Comment by derks** [comment]
Should pass now in Travis.. not sure how to re-trigger that via GH/Pull Request though.

**Comment by XhmikosR** [comment]
You should squash the two commits into one. Travis will get triggered in both cases.

**Comment by derks** [comment]
Closing this PR and starting fresh... little unfamiliar with rebasing, and after pulling in everything else I can't quite get it clean.  Will submit a new PR.  Sorry for the noise.

**Pull request closed without merging**
