### PR TITLE
Update format of eupl-1.2.txt

### PR DESCRIPTION
**Pull request by bbenno**
Use the official UTF-8 format version from
<https://joinup.ec.europa.eu/sites/default/files/custom-page/attachment/2020-03/EUPL-1.2%20EN.txt>
that is linked on
<https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12>

Advantage: better readability (especially header and "_copyright notice for the Work: ..._" line)

### CODE REVIEW

**Comment by mlinksva** [comment]
Thanks @bbenno it appears that there are some extra ‘ characters in our copy, not sure how we missed that before, appears to be in #523 which added EUPL-1.2.

Because of this I'll go ahead and merge, though I [usually](https://github.com/github/choosealicense.com/pull/784#issuecomment-727276600) prefer that changes are made first in https://github.com/spdx/license-list-XML/ if applicable and we align with that. I'd still encourage making sure https://github.com/spdx/license-list-XML/blob/master/src/EUPL-1.2.xml is updated -- at the least a crossref to the new source URL you mention seems appropriate.

**Comment by bbenno** [comment]
> Thanks @bbenno it appears that there are some extra ‘ characters in our copy, not sure how we missed that before, appears to be in #523 which added EUPL-1.2.
> 
> Because of this I'll go ahead and merge, though I [usually](https://github.com/github/choosealicense.com/pull/784#issuecomment-727276600) prefer that changes are made first in https://github.com/spdx/license-list-XML/ if applicable and we align with that.

Oh, didn't know that. Sorry...
It seems like I skipped the corresponding section in [CONTRIBUTE](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license) and only read the `Making changes` section.

> I'd still encourage making sure https://github.com/spdx/license-list-XML/blob/master/src/EUPL-1.2.xml is updated -- at the least a crossref to the new source URL you mention seems appropriate.

I will add the new crossref as suggested.

**Comment by bbenno** [comment]
@mlinksva 
I am very uncertain about further changes in [spdx/license-list-XML](https://github.com/spdx/license-list-XML) as the changes of this #797 mainly introduced some blank lines and changed the bullet sign of the unordered lists.

The only that I could imagine applying to [spdx/license-list-XML](https://github.com/spdx/license-list-XML) would be the header centering :one: as well as the removal of list syntax at the bottom most lines :two:.

:one:: I think (but definitly not sure) the left align of the header might come from the `<p>` enclosure...

**Comment by mlinksva** [comment]
Looking at the wdiff between the EC version now also in this repo and https://github.com/spdx/license-list-data/blob/2e20899c0504ff6c0acfcc1b0994d7163ce46939/text/EUPL-1.2.txt which is rendered from https://github.com/spdx/license-list-XML/blob/master/src/EUPL-1.2.xml it looks like the only change representable in the XML version would be replacing — with - for bullets.

**Pull request merged**
