### PR TITLE
Short description of GPL on homepage

### PR DESCRIPTION
**Pull request by ghost**
Small update of the language in GPL short presentation to convey the copyleft requirement some better. I hope it's better... Also it follows @Lennie's suggestion on downstream recipients ("to whomever you distribute to"), although I'm not sure that particular part, while correct, is essential to the license.

The short description should IMHO cover the essentials, one needs to know, it's way too short for specific details... This is probably not yet ideal. Thanks for taking a look though.

### CODE REVIEW

**Comment by benbalter** [comment]
All for clarification, but don't know that I'd support anything that lengthens the summary.

> anyone distributing the code, or a derivative work of the code, to make the complete source available under the same terms to whomever they distribute to

Perhaps:

> anyone who distributes your code or a derivative work to make the source available under the same terms

**Comment by ghost** [comment]
Shortened as noted. Thank you, IMO it's better for the first part of GPL short description, it conveys the main point.

**Comment by benbalter** [comment]
I'm :+1:, @Haacked ?

**Comment by Lennie** [comment]
It makes me happy, push it to the website already ;-)

Then you can close this and at least https://github.com/github/choosealicense.com/issues/66

**Comment by haacked** [comment]
Love it! Same length as before, but more clear! 
obama-applause

**Pull request merged**
