### PR TITLE
Use HTTPS link in MPL

### PR DESCRIPTION
**Pull request by fmarier**
Update the link in the MPL license text to match the official license text from https://www.mozilla.org/en-US/MPL/

### CODE REVIEW

**Review by Dioliode — APPROVED** [review]
DioX

**Review by Dioliode — APPROVED** [review]
DioX

**Comment by Nadermohamad** [comment]
Thanks

**Review by Dioliode — APPROVED** [review]
DioX

**Review by Dioliode — APPROVED** [review]
DioX

**Comment by DeflateAwning** [comment]
Please just merge this change

**Review by Dioliode — APPROVED** [review]
DioX

**Comment by mlinksva** [comment]
Thanks. I forgot about this, reminded by seeing https://github.com/spdx/license-list-XML/pull/2498 merged.

**Review by amethystens — COMMENTED** [review]
[]()

**Pull request merged**
