### PR TITLE
Create whitelist of non-OSI approved licenses

### PR DESCRIPTION
**Pull request by benbalter**
Fixes https://github.com/github/choosealicense.com/issues/281.

### CODE REVIEW

**Comment by parkr** [comment]
Maintaining OSI approval appears to me to be valuable. It gives each license proposal an extra layer of validation (and, as you have noted earlier, trims the long tail considerably). For licenses this project is interested in keeping track of that the OSI has not approved should be added to a whitelist whose membership is excluded from the OSI validation.

**Comment by benbalter** [comment]
This pull request as written just simplifies an existing test (moving two conditionals to a constant) and will get tests green on master. Merging, but glad to continue the discussion over in #281.

**Comment by parkr** [comment]
Tiny nit: would you mind renaming this PR to describe the changes that were merged?

**Comment by benbalter** [comment]
@parkr really good call. Done. Thanks.

**Pull request merged**
