### PR TITLE
Artistic license is not copyleft

### PR DESCRIPTION
**Pull request by ghost**
- Artistic license is not copyleft, it doesn't require disclose source. Reported in #73
- Also added a proposal for the description, following the information provided by @dan2097

### CODE REVIEW

**Comment by benbalter** [comment]
> A license that&#8217;s heavily favored by the Perl community. Provided that modified versions do not prevent the user from running the standard version, this license does not require distributions of modified versions to provide the source code.

All for this, would love to see if we can't tighten it up a bit. Don't know that we need to explicitly note that it's not copyleft (we don't do that on the other permissive licenses):

> Heavily favored by the Perl community, the Artistic license requires that modified versions of the software do not prevent users from running the standard version.

**Comment by ghost** [comment]
@benbalter Updated as noted. It appears that in some reading, Artistic is taken as if it would be copyleft, but I guess it's only some mistake, and you're right, the description is not the place to clarify that... :smile: The removal of disclose source fixes it.

**Comment by benbalter** [comment]
:+1:, @Haacked ?

**Comment by benbalter** [comment]
also, @engelnyst thanks for taking the time to look into all this. Not super glamorous, but incredibly important and incredibly helpful. Glad to see your contributions. Thank you.

**Comment by haacked** [comment]
thumbs-up-peyton

Thanks! Sorry for the delay!

**Pull request merged**
