### PR TITLE
update title match actual name of license

### PR DESCRIPTION
**Pull request by ghost**
you might not like the title but that doesn't mean you can change the name

### CODE REVIEW

**Comment by jhabdas** [comment]
p.s. your build broke

**Comment by mlinksva** [comment]
We use the names cataloged at SPDX, indeed we have a test to ensure we're using those names. Feel free to take it up with them. Thanks!

**Comment by jhabdas** [comment]
Nice hand wave.

**Comment by ghost** [comment]
Thanks @mlinksva I [sent in a pull](https://github.com/spdx/license-list-XML/pull/764) to try and address the issue in a way I hope others will find acceptable while raising the visibility of this excellent license.

**Pull request closed without merging**
