### PR TITLE
Use HTTPS for licences if available

### PR DESCRIPTION
**Pull request by TuxCoding**
I checked if the links in the licenses are reachable with HTTPS (including if they have valid certificate). If they are I changed the url to use HTTPS, but kept the other ones to plain HTTP like: `http://www.wtfpl.net/`

### CODE REVIEW

**Comment by mlinksva** [comment]
@games647 good idea for the links in frontmatter, thanks. But I'd rather not change license texts at all. Could you update this to only change frontmatter links?

**Comment by TuxCoding** [comment]
>But I'd rather not change license texts at all. 

Should I then change the text of the unlicense too, because the original version contains only a HTTP link?

https://github.com/github/choosealicense.com/blob/c229dccb6d356729eecfe4ac20cdf26906c1e29e/_licenses/unlicense.txt#L53

vs

https://unlicense.org/UNLICENSE (without HTTPS)

**Comment by mlinksva** [comment]
@games647 yes and thank you!

I shouldn't have merged https://github.com/github/choosealicense.com/pull/520 -- I remember thinking the change was to the frontmatter, but obviously was only seeing what I thought I should see. 😳

**Comment by TuxCoding** [comment]
Done

**Comment by mlinksva** [comment]
Thanks again. Annoying that [this](https://travis-ci.org/github/choosealicense.com/builds/281991806#L899-L903) is consistently happening in CI-run tests:

> - ./_site/existing/index.html
>  *  External link https://www.openbsd.org/policy.html failed: response code 0 means something's wrong.
>             It's possible libcurl couldn't connect to the server or perhaps the request timed out.
>            Sometimes, making too many requests at once also breaks things.
>             Either way, the return message (if any) from the server is: SSL connect error

Though https://www.ssllabs.com/ssltest/analyze.html?d=www.openbsd.org obtains an 'A' rating.

I'll go ahead and merge as it seems that if there's a problem, it's with the test environment.

**Comment by TuxCoding** [comment]
It could be because it's a let's encrypt certificate and the certificate storage on travis isn't up to date to support let's encrypt.

**Pull request merged**
